// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/janghanul090801/go-backend-clean-architecture-fiber/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PolicyRepository is an autogenerated mock type for the PolicyRepository type
type PolicyRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, policy
func (_m *PolicyRepository) Create(c context.Context, policy *domain.Policy) (*domain.Policy, error) {
	ret := _m.Called(c, policy)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Policy) (*domain.Policy, error)); ok {
		return rf(c, policy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Policy) *domain.Policy); ok {
		r0 = rf(c, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Policy) error); ok {
		r1 = rf(c, policy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: c, id
func (_m *PolicyRepository) Delete(c context.Context, id *uuid.UUID) error {
	ret := _m.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) error); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: c
func (_m *PolicyRepository) FindAll(c context.Context) ([]*domain.Policy, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Policy, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Policy); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByRegionCode provides a mock function with given fields: c, regionCode
func (_m *PolicyRepository) FindAllByRegionCode(c context.Context, regionCode int) ([]*domain.Policy, error) {
	ret := _m.Called(c, regionCode)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByRegionCode")
	}

	var r0 []*domain.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Policy, error)); ok {
		return rf(c, regionCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.Policy); ok {
		r0 = rf(c, regionCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(c, regionCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByRegionCodeAndActive provides a mock function with given fields: c, regionCode
func (_m *PolicyRepository) FindAllByRegionCodeAndActive(c context.Context, regionCode int) ([]*domain.Policy, error) {
	ret := _m.Called(c, regionCode)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByRegionCodeAndActive")
	}

	var r0 []*domain.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Policy, error)); ok {
		return rf(c, regionCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.Policy); ok {
		r0 = rf(c, regionCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(c, regionCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: c, id
func (_m *PolicyRepository) FindByID(c context.Context, id *uuid.UUID) (*domain.Policy, error) {
	ret := _m.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) (*domain.Policy, error)); ok {
		return rf(c, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) *domain.Policy); ok {
		r0 = rf(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByTitle provides a mock function with given fields: c, title
func (_m *PolicyRepository) FindByTitle(c context.Context, title string) (*domain.Policy, error) {
	ret := _m.Called(c, title)

	if len(ret) == 0 {
		panic("no return value specified for FindByTitle")
	}

	var r0 *domain.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Policy, error)); ok {
		return rf(c, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Policy); ok {
		r0 = rf(c, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPolicyRepository creates a new instance of PolicyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PolicyRepository {
	mock := &PolicyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
