// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/janghanul090801/go-backend-clean-architecture-fiber/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PolicyMatchRepository is an autogenerated mock type for the PolicyMatchRepository type
type PolicyMatchRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, policyMatch
func (_m *PolicyMatchRepository) Create(c context.Context, policyMatch *domain.PolicyMatch) (*domain.PolicyMatch, error) {
	ret := _m.Called(c, policyMatch)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.PolicyMatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PolicyMatch) (*domain.PolicyMatch, error)); ok {
		return rf(c, policyMatch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PolicyMatch) *domain.PolicyMatch); ok {
		r0 = rf(c, policyMatch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PolicyMatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.PolicyMatch) error); ok {
		r1 = rf(c, policyMatch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByUserID provides a mock function with given fields: c, userID
func (_m *PolicyMatchRepository) FindAllByUserID(c context.Context, userID *uuid.UUID) ([]*domain.PolicyMatch, error) {
	ret := _m.Called(c, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []*domain.PolicyMatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) ([]*domain.PolicyMatch, error)); ok {
		return rf(c, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) []*domain.PolicyMatch); ok {
		r0 = rf(c, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PolicyMatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID) error); ok {
		r1 = rf(c, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByUserIDAndStatus provides a mock function with given fields: c, userID, status
func (_m *PolicyMatchRepository) FindAllByUserIDAndStatus(c context.Context, userID *uuid.UUID, status domain.Match) ([]*domain.PolicyMatch, error) {
	ret := _m.Called(c, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserIDAndStatus")
	}

	var r0 []*domain.PolicyMatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID, domain.Match) ([]*domain.PolicyMatch, error)); ok {
		return rf(c, userID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID, domain.Match) []*domain.PolicyMatch); ok {
		r0 = rf(c, userID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PolicyMatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID, domain.Match) error); ok {
		r1 = rf(c, userID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, id, status
func (_m *PolicyMatchRepository) Update(c context.Context, id *uuid.UUID, status domain.Match) (*domain.PolicyMatch, error) {
	ret := _m.Called(c, id, status)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.PolicyMatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID, domain.Match) (*domain.PolicyMatch, error)); ok {
		return rf(c, id, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID, domain.Match) *domain.PolicyMatch); ok {
		r0 = rf(c, id, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PolicyMatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID, domain.Match) error); ok {
		r1 = rf(c, id, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPolicyMatchRepository creates a new instance of PolicyMatchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicyMatchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PolicyMatchRepository {
	mock := &PolicyMatchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
