// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/janghanul090801/pico-backend/domain"
	mock "github.com/stretchr/testify/mock"
)

// ProfileUseCase is an autogenerated mock type for the ProfileUseCase type
type ProfileUseCase struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: c, userID
func (_m *ProfileUseCase) GetByID(c context.Context, userID *domain.ID) (*domain.Profile, error) {
	ret := _m.Called(c, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ID) (*domain.Profile, error)); ok {
		return rf(c, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ID) *domain.Profile); ok {
		r0 = rf(c, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.ID) error); ok {
		r1 = rf(c, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: c, ID, params
func (_m *ProfileUseCase) Update(c context.Context, ID *domain.ID, params *domain.ProfileUpdateRequest) (*domain.Profile, error) {
	ret := _m.Called(c, ID, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ID, *domain.ProfileUpdateRequest) (*domain.Profile, error)); ok {
		return rf(c, ID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ID, *domain.ProfileUpdateRequest) *domain.Profile); ok {
		r0 = rf(c, ID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.ID, *domain.ProfileUpdateRequest) error); ok {
		r1 = rf(c, ID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProfileUseCase creates a new instance of ProfileUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileUseCase {
	mock := &ProfileUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
