// Code generated by ent, DO NOT EDIT.

package governmentpolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldDescription, v))
}

// RegionCode applies equality check predicate on the "region_code" field. It's identical to RegionCodeEQ.
func RegionCode(v int) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldRegionCode, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldEndDate, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldAddress, v))
}

// Latitude applies equality check predicate on the "latitude" field. It's identical to LatitudeEQ.
func Latitude(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldLatitude, v))
}

// Longitude applies equality check predicate on the "longitude" field. It's identical to LongitudeEQ.
func Longitude(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldLongitude, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldContainsFold(FieldDescription, v))
}

// RegionCodeEQ applies the EQ predicate on the "region_code" field.
func RegionCodeEQ(v int) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldRegionCode, v))
}

// RegionCodeNEQ applies the NEQ predicate on the "region_code" field.
func RegionCodeNEQ(v int) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNEQ(FieldRegionCode, v))
}

// RegionCodeIn applies the In predicate on the "region_code" field.
func RegionCodeIn(vs ...int) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldIn(FieldRegionCode, vs...))
}

// RegionCodeNotIn applies the NotIn predicate on the "region_code" field.
func RegionCodeNotIn(vs ...int) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNotIn(FieldRegionCode, vs...))
}

// RegionCodeGT applies the GT predicate on the "region_code" field.
func RegionCodeGT(v int) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGT(FieldRegionCode, v))
}

// RegionCodeGTE applies the GTE predicate on the "region_code" field.
func RegionCodeGTE(v int) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGTE(FieldRegionCode, v))
}

// RegionCodeLT applies the LT predicate on the "region_code" field.
func RegionCodeLT(v int) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLT(FieldRegionCode, v))
}

// RegionCodeLTE applies the LTE predicate on the "region_code" field.
func RegionCodeLTE(v int) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLTE(FieldRegionCode, v))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLTE(FieldStartDate, v))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLTE(FieldEndDate, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldContainsFold(FieldAddress, v))
}

// LatitudeEQ applies the EQ predicate on the "latitude" field.
func LatitudeEQ(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldLatitude, v))
}

// LatitudeNEQ applies the NEQ predicate on the "latitude" field.
func LatitudeNEQ(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNEQ(FieldLatitude, v))
}

// LatitudeIn applies the In predicate on the "latitude" field.
func LatitudeIn(vs ...float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldIn(FieldLatitude, vs...))
}

// LatitudeNotIn applies the NotIn predicate on the "latitude" field.
func LatitudeNotIn(vs ...float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNotIn(FieldLatitude, vs...))
}

// LatitudeGT applies the GT predicate on the "latitude" field.
func LatitudeGT(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGT(FieldLatitude, v))
}

// LatitudeGTE applies the GTE predicate on the "latitude" field.
func LatitudeGTE(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGTE(FieldLatitude, v))
}

// LatitudeLT applies the LT predicate on the "latitude" field.
func LatitudeLT(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLT(FieldLatitude, v))
}

// LatitudeLTE applies the LTE predicate on the "latitude" field.
func LatitudeLTE(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLTE(FieldLatitude, v))
}

// LongitudeEQ applies the EQ predicate on the "longitude" field.
func LongitudeEQ(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldEQ(FieldLongitude, v))
}

// LongitudeNEQ applies the NEQ predicate on the "longitude" field.
func LongitudeNEQ(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNEQ(FieldLongitude, v))
}

// LongitudeIn applies the In predicate on the "longitude" field.
func LongitudeIn(vs ...float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldIn(FieldLongitude, vs...))
}

// LongitudeNotIn applies the NotIn predicate on the "longitude" field.
func LongitudeNotIn(vs ...float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldNotIn(FieldLongitude, vs...))
}

// LongitudeGT applies the GT predicate on the "longitude" field.
func LongitudeGT(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGT(FieldLongitude, v))
}

// LongitudeGTE applies the GTE predicate on the "longitude" field.
func LongitudeGTE(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldGTE(FieldLongitude, v))
}

// LongitudeLT applies the LT predicate on the "longitude" field.
func LongitudeLT(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLT(FieldLongitude, v))
}

// LongitudeLTE applies the LTE predicate on the "longitude" field.
func LongitudeLTE(v float64) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.FieldLTE(FieldLongitude, v))
}

// HasMatches applies the HasEdge predicate on the "matches" edge.
func HasMatches() predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MatchesTable, MatchesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMatchesWith applies the HasEdge predicate on the "matches" edge with a given conditions (other predicates).
func HasMatchesWith(preds ...predicate.PolicyMatch) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(func(s *sql.Selector) {
		step := newMatchesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GovernmentPolicy) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GovernmentPolicy) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GovernmentPolicy) predicate.GovernmentPolicy {
	return predicate.GovernmentPolicy(sql.NotPredicates(p))
}
