// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GovernmentPoliciesColumns holds the columns for the "government_policies" table.
	GovernmentPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "region_code", Type: field.TypeInt},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime},
		{Name: "address", Type: field.TypeString},
		{Name: "latitude", Type: field.TypeFloat64},
		{Name: "longitude", Type: field.TypeFloat64},
	}
	// GovernmentPoliciesTable holds the schema information for the "government_policies" table.
	GovernmentPoliciesTable = &schema.Table{
		Name:       "government_policies",
		Columns:    GovernmentPoliciesColumns,
		PrimaryKey: []*schema.Column{GovernmentPoliciesColumns[0]},
	}
	// PolicyMatchesColumns holds the columns for the "policy_matches" table.
	PolicyMatchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "match", Type: field.TypeEnum, Enums: []string{"POSSIBLE", "UNCERTAIN", "IMPOSSIBLE"}},
		{Name: "government_policy_matches", Type: field.TypeUUID},
		{Name: "user_policy_matches", Type: field.TypeUUID},
	}
	// PolicyMatchesTable holds the schema information for the "policy_matches" table.
	PolicyMatchesTable = &schema.Table{
		Name:       "policy_matches",
		Columns:    PolicyMatchesColumns,
		PrimaryKey: []*schema.Column{PolicyMatchesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "policy_matches_government_policies_matches",
				Columns:    []*schema.Column{PolicyMatchesColumns[2]},
				RefColumns: []*schema.Column{GovernmentPoliciesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "policy_matches_users_policy_matches",
				Columns:    []*schema.Column{PolicyMatchesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "age", Type: field.TypeInt},
		{Name: "region", Type: field.TypeString},
		{Name: "gender", Type: field.TypeEnum, Enums: []string{"MALE", "FEMALE", "OTHER"}},
		{Name: "is_student", Type: field.TypeBool, Default: false},
		{Name: "is_youth", Type: field.TypeBool, Default: false},
		{Name: "is_pregnant", Type: field.TypeBool, Nullable: true},
		{Name: "is_business", Type: field.TypeBool, Nullable: true},
		{Name: "interests", Type: field.TypeJSON, Nullable: true},
		{Name: "is_disabled", Type: field.TypeBool, Default: false},
		{Name: "nationality", Type: field.TypeEnum, Enums: []string{"DOMESTIC", "FOREIGN"}},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GovernmentPoliciesTable,
		PolicyMatchesTable,
		UsersTable,
	}
)

func init() {
	PolicyMatchesTable.ForeignKeys[0].RefTable = GovernmentPoliciesTable
	PolicyMatchesTable.ForeignKeys[1].RefTable = UsersTable
}
