// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FavoritesColumns holds the columns for the "favorites" table.
	FavoritesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "government_policy_favorites", Type: field.TypeUUID},
		{Name: "user_favorites", Type: field.TypeUUID},
	}
	// FavoritesTable holds the schema information for the "favorites" table.
	FavoritesTable = &schema.Table{
		Name:       "favorites",
		Columns:    FavoritesColumns,
		PrimaryKey: []*schema.Column{FavoritesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "favorites_government_policies_favorites",
				Columns:    []*schema.Column{FavoritesColumns[2]},
				RefColumns: []*schema.Column{GovernmentPoliciesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "favorites_users_favorites",
				Columns:    []*schema.Column{FavoritesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// GovernmentPoliciesColumns holds the columns for the "government_policies" table.
	GovernmentPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "region_code", Type: field.TypeInt},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime},
		{Name: "address", Type: field.TypeString},
		{Name: "latitude", Type: field.TypeFloat64},
		{Name: "longitude", Type: field.TypeFloat64},
		{Name: "condition", Type: field.TypeJSON},
	}
	// GovernmentPoliciesTable holds the schema information for the "government_policies" table.
	GovernmentPoliciesTable = &schema.Table{
		Name:       "government_policies",
		Columns:    GovernmentPoliciesColumns,
		PrimaryKey: []*schema.Column{GovernmentPoliciesColumns[0]},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "type", Type: field.TypeInt},
		{Name: "message", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "is_read", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_notifications", Type: field.TypeUUID},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notifications_users_notifications",
				Columns:    []*schema.Column{NotificationsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PolicyMatchesColumns holds the columns for the "policy_matches" table.
	PolicyMatchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "match", Type: field.TypeEnum, Enums: []string{"POSSIBLE", "UNCERTAIN", "IMPOSSIBLE"}},
		{Name: "probability", Type: field.TypeInt, Nullable: true},
		{Name: "comment", Type: field.TypeString, Nullable: true},
		{Name: "government_policy_matches", Type: field.TypeUUID},
		{Name: "user_policy_matches", Type: field.TypeUUID},
	}
	// PolicyMatchesTable holds the schema information for the "policy_matches" table.
	PolicyMatchesTable = &schema.Table{
		Name:       "policy_matches",
		Columns:    PolicyMatchesColumns,
		PrimaryKey: []*schema.Column{PolicyMatchesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "policy_matches_government_policies_matches",
				Columns:    []*schema.Column{PolicyMatchesColumns[4]},
				RefColumns: []*schema.Column{GovernmentPoliciesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "policy_matches_users_policy_matches",
				Columns:    []*schema.Column{PolicyMatchesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "age", Type: field.TypeInt},
		{Name: "region_code", Type: field.TypeInt},
		{Name: "gender", Type: field.TypeEnum, Enums: []string{"MALE", "FEMALE", "OTHER"}},
		{Name: "is_student", Type: field.TypeBool, Default: false},
		{Name: "is_youth", Type: field.TypeBool, Default: false},
		{Name: "is_pregnant", Type: field.TypeBool, Default: false},
		{Name: "is_business", Type: field.TypeBool, Default: false},
		{Name: "is_foreign", Type: field.TypeBool, Default: false},
		{Name: "is_disabled", Type: field.TypeBool, Default: false},
		{Name: "interests", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FavoritesTable,
		GovernmentPoliciesTable,
		NotificationsTable,
		PolicyMatchesTable,
		UsersTable,
	}
)

func init() {
	FavoritesTable.ForeignKeys[0].RefTable = GovernmentPoliciesTable
	FavoritesTable.ForeignKeys[1].RefTable = UsersTable
	NotificationsTable.ForeignKeys[0].RefTable = UsersTable
	PolicyMatchesTable.ForeignKeys[0].RefTable = GovernmentPoliciesTable
	PolicyMatchesTable.ForeignKeys[1].RefTable = UsersTable
}
