// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/ent/favorite"
	"github.com/janghanul090801/pico-backend/ent/governmentpolicy"
	"github.com/janghanul090801/pico-backend/ent/user"
)

// Favorite is the model entity for the Favorite schema.
type Favorite struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FavoriteQuery when eager-loading is set.
	Edges                       FavoriteEdges `json:"edges"`
	government_policy_favorites *uuid.UUID
	user_favorites              *uuid.UUID
	selectValues                sql.SelectValues
}

// FavoriteEdges holds the relations/edges for other nodes in the graph.
type FavoriteEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Policy holds the value of the policy edge.
	Policy *GovernmentPolicy `json:"policy,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FavoriteEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PolicyOrErr returns the Policy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FavoriteEdges) PolicyOrErr() (*GovernmentPolicy, error) {
	if e.Policy != nil {
		return e.Policy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: governmentpolicy.Label}
	}
	return nil, &NotLoadedError{edge: "policy"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Favorite) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case favorite.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case favorite.FieldID:
			values[i] = new(uuid.UUID)
		case favorite.ForeignKeys[0]: // government_policy_favorites
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case favorite.ForeignKeys[1]: // user_favorites
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Favorite fields.
func (_m *Favorite) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case favorite.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case favorite.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case favorite.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field government_policy_favorites", values[i])
			} else if value.Valid {
				_m.government_policy_favorites = new(uuid.UUID)
				*_m.government_policy_favorites = *value.S.(*uuid.UUID)
			}
		case favorite.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_favorites", values[i])
			} else if value.Valid {
				_m.user_favorites = new(uuid.UUID)
				*_m.user_favorites = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Favorite.
// This includes values selected through modifiers, order, etc.
func (_m *Favorite) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Favorite entity.
func (_m *Favorite) QueryUser() *UserQuery {
	return NewFavoriteClient(_m.config).QueryUser(_m)
}

// QueryPolicy queries the "policy" edge of the Favorite entity.
func (_m *Favorite) QueryPolicy() *GovernmentPolicyQuery {
	return NewFavoriteClient(_m.config).QueryPolicy(_m)
}

// Update returns a builder for updating this Favorite.
// Note that you need to call Favorite.Unwrap() before calling this method if this Favorite
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Favorite) Update() *FavoriteUpdateOne {
	return NewFavoriteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Favorite entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Favorite) Unwrap() *Favorite {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Favorite is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Favorite) String() string {
	var builder strings.Builder
	builder.WriteString("Favorite(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Favorites is a parsable slice of Favorite.
type Favorites []*Favorite
