// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/janghanul090801/go-backend-clean-architecture-fiber/ent/governmentpolicy"
	"github.com/janghanul090801/go-backend-clean-architecture-fiber/ent/predicate"
)

// GovernmentPolicyDelete is the builder for deleting a GovernmentPolicy entity.
type GovernmentPolicyDelete struct {
	config
	hooks    []Hook
	mutation *GovernmentPolicyMutation
}

// Where appends a list predicates to the GovernmentPolicyDelete builder.
func (_d *GovernmentPolicyDelete) Where(ps ...predicate.GovernmentPolicy) *GovernmentPolicyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GovernmentPolicyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GovernmentPolicyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GovernmentPolicyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(governmentpolicy.Table, sqlgraph.NewFieldSpec(governmentpolicy.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GovernmentPolicyDeleteOne is the builder for deleting a single GovernmentPolicy entity.
type GovernmentPolicyDeleteOne struct {
	_d *GovernmentPolicyDelete
}

// Where appends a list predicates to the GovernmentPolicyDelete builder.
func (_d *GovernmentPolicyDeleteOne) Where(ps ...predicate.GovernmentPolicy) *GovernmentPolicyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GovernmentPolicyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{governmentpolicy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GovernmentPolicyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
