// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/domain"
	"github.com/janghanul090801/pico-backend/ent/favorite"
	"github.com/janghanul090801/pico-backend/ent/governmentpolicy"
	"github.com/janghanul090801/pico-backend/ent/policymatch"
)

// GovernmentPolicyCreate is the builder for creating a GovernmentPolicy entity.
type GovernmentPolicyCreate struct {
	config
	mutation *GovernmentPolicyMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *GovernmentPolicyCreate) SetTitle(v string) *GovernmentPolicyCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *GovernmentPolicyCreate) SetDescription(v string) *GovernmentPolicyCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetRegionCode sets the "region_code" field.
func (_c *GovernmentPolicyCreate) SetRegionCode(v int) *GovernmentPolicyCreate {
	_c.mutation.SetRegionCode(v)
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *GovernmentPolicyCreate) SetStartDate(v time.Time) *GovernmentPolicyCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *GovernmentPolicyCreate) SetEndDate(v time.Time) *GovernmentPolicyCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *GovernmentPolicyCreate) SetAddress(v string) *GovernmentPolicyCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetLatitude sets the "latitude" field.
func (_c *GovernmentPolicyCreate) SetLatitude(v float64) *GovernmentPolicyCreate {
	_c.mutation.SetLatitude(v)
	return _c
}

// SetLongitude sets the "longitude" field.
func (_c *GovernmentPolicyCreate) SetLongitude(v float64) *GovernmentPolicyCreate {
	_c.mutation.SetLongitude(v)
	return _c
}

// SetCondition sets the "condition" field.
func (_c *GovernmentPolicyCreate) SetCondition(v domain.PolicyCondition) *GovernmentPolicyCreate {
	_c.mutation.SetCondition(v)
	return _c
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (_c *GovernmentPolicyCreate) SetNillableCondition(v *domain.PolicyCondition) *GovernmentPolicyCreate {
	if v != nil {
		_c.SetCondition(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GovernmentPolicyCreate) SetID(v uuid.UUID) *GovernmentPolicyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GovernmentPolicyCreate) SetNillableID(v *uuid.UUID) *GovernmentPolicyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddMatchIDs adds the "matches" edge to the PolicyMatch entity by IDs.
func (_c *GovernmentPolicyCreate) AddMatchIDs(ids ...uuid.UUID) *GovernmentPolicyCreate {
	_c.mutation.AddMatchIDs(ids...)
	return _c
}

// AddMatches adds the "matches" edges to the PolicyMatch entity.
func (_c *GovernmentPolicyCreate) AddMatches(v ...*PolicyMatch) *GovernmentPolicyCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMatchIDs(ids...)
}

// AddFavoriteIDs adds the "favorites" edge to the Favorite entity by IDs.
func (_c *GovernmentPolicyCreate) AddFavoriteIDs(ids ...uuid.UUID) *GovernmentPolicyCreate {
	_c.mutation.AddFavoriteIDs(ids...)
	return _c
}

// AddFavorites adds the "favorites" edges to the Favorite entity.
func (_c *GovernmentPolicyCreate) AddFavorites(v ...*Favorite) *GovernmentPolicyCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFavoriteIDs(ids...)
}

// Mutation returns the GovernmentPolicyMutation object of the builder.
func (_c *GovernmentPolicyCreate) Mutation() *GovernmentPolicyMutation {
	return _c.mutation
}

// Save creates the GovernmentPolicy in the database.
func (_c *GovernmentPolicyCreate) Save(ctx context.Context) (*GovernmentPolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GovernmentPolicyCreate) SaveX(ctx context.Context) *GovernmentPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GovernmentPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GovernmentPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GovernmentPolicyCreate) defaults() {
	if _, ok := _c.mutation.Condition(); !ok {
		v := governmentpolicy.DefaultCondition
		_c.mutation.SetCondition(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := governmentpolicy.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GovernmentPolicyCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "GovernmentPolicy.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := governmentpolicy.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "GovernmentPolicy.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "GovernmentPolicy.description"`)}
	}
	if _, ok := _c.mutation.RegionCode(); !ok {
		return &ValidationError{Name: "region_code", err: errors.New(`ent: missing required field "GovernmentPolicy.region_code"`)}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "GovernmentPolicy.start_date"`)}
	}
	if _, ok := _c.mutation.EndDate(); !ok {
		return &ValidationError{Name: "end_date", err: errors.New(`ent: missing required field "GovernmentPolicy.end_date"`)}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "GovernmentPolicy.address"`)}
	}
	if _, ok := _c.mutation.Latitude(); !ok {
		return &ValidationError{Name: "latitude", err: errors.New(`ent: missing required field "GovernmentPolicy.latitude"`)}
	}
	if _, ok := _c.mutation.Longitude(); !ok {
		return &ValidationError{Name: "longitude", err: errors.New(`ent: missing required field "GovernmentPolicy.longitude"`)}
	}
	if _, ok := _c.mutation.Condition(); !ok {
		return &ValidationError{Name: "condition", err: errors.New(`ent: missing required field "GovernmentPolicy.condition"`)}
	}
	return nil
}

func (_c *GovernmentPolicyCreate) sqlSave(ctx context.Context) (*GovernmentPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GovernmentPolicyCreate) createSpec() (*GovernmentPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &GovernmentPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(governmentpolicy.Table, sqlgraph.NewFieldSpec(governmentpolicy.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(governmentpolicy.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(governmentpolicy.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.RegionCode(); ok {
		_spec.SetField(governmentpolicy.FieldRegionCode, field.TypeInt, value)
		_node.RegionCode = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(governmentpolicy.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(governmentpolicy.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(governmentpolicy.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Latitude(); ok {
		_spec.SetField(governmentpolicy.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = value
	}
	if value, ok := _c.mutation.Longitude(); ok {
		_spec.SetField(governmentpolicy.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = value
	}
	if value, ok := _c.mutation.Condition(); ok {
		_spec.SetField(governmentpolicy.FieldCondition, field.TypeJSON, value)
		_node.Condition = value
	}
	if nodes := _c.mutation.MatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   governmentpolicy.MatchesTable,
			Columns: []string{governmentpolicy.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FavoritesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   governmentpolicy.FavoritesTable,
			Columns: []string{governmentpolicy.FavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(favorite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GovernmentPolicyCreateBulk is the builder for creating many GovernmentPolicy entities in bulk.
type GovernmentPolicyCreateBulk struct {
	config
	err      error
	builders []*GovernmentPolicyCreate
}

// Save creates the GovernmentPolicy entities in the database.
func (_c *GovernmentPolicyCreateBulk) Save(ctx context.Context) ([]*GovernmentPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GovernmentPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GovernmentPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GovernmentPolicyCreateBulk) SaveX(ctx context.Context) []*GovernmentPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GovernmentPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GovernmentPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
