// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/ent/governmentpolicy"
	"github.com/janghanul090801/pico-backend/ent/policymatch"
	"github.com/janghanul090801/pico-backend/ent/predicate"
)

// GovernmentPolicyUpdate is the builder for updating GovernmentPolicy entities.
type GovernmentPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *GovernmentPolicyMutation
}

// Where appends a list predicates to the GovernmentPolicyUpdate builder.
func (_u *GovernmentPolicyUpdate) Where(ps ...predicate.GovernmentPolicy) *GovernmentPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *GovernmentPolicyUpdate) SetTitle(v string) *GovernmentPolicyUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *GovernmentPolicyUpdate) SetNillableTitle(v *string) *GovernmentPolicyUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GovernmentPolicyUpdate) SetDescription(v string) *GovernmentPolicyUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GovernmentPolicyUpdate) SetNillableDescription(v *string) *GovernmentPolicyUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetRegionCode sets the "region_code" field.
func (_u *GovernmentPolicyUpdate) SetRegionCode(v int) *GovernmentPolicyUpdate {
	_u.mutation.ResetRegionCode()
	_u.mutation.SetRegionCode(v)
	return _u
}

// SetNillableRegionCode sets the "region_code" field if the given value is not nil.
func (_u *GovernmentPolicyUpdate) SetNillableRegionCode(v *int) *GovernmentPolicyUpdate {
	if v != nil {
		_u.SetRegionCode(*v)
	}
	return _u
}

// AddRegionCode adds value to the "region_code" field.
func (_u *GovernmentPolicyUpdate) AddRegionCode(v int) *GovernmentPolicyUpdate {
	_u.mutation.AddRegionCode(v)
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *GovernmentPolicyUpdate) SetStartDate(v time.Time) *GovernmentPolicyUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *GovernmentPolicyUpdate) SetNillableStartDate(v *time.Time) *GovernmentPolicyUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *GovernmentPolicyUpdate) SetEndDate(v time.Time) *GovernmentPolicyUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *GovernmentPolicyUpdate) SetNillableEndDate(v *time.Time) *GovernmentPolicyUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *GovernmentPolicyUpdate) SetAddress(v string) *GovernmentPolicyUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *GovernmentPolicyUpdate) SetNillableAddress(v *string) *GovernmentPolicyUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *GovernmentPolicyUpdate) SetLatitude(v float64) *GovernmentPolicyUpdate {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *GovernmentPolicyUpdate) SetNillableLatitude(v *float64) *GovernmentPolicyUpdate {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *GovernmentPolicyUpdate) AddLatitude(v float64) *GovernmentPolicyUpdate {
	_u.mutation.AddLatitude(v)
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *GovernmentPolicyUpdate) SetLongitude(v float64) *GovernmentPolicyUpdate {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *GovernmentPolicyUpdate) SetNillableLongitude(v *float64) *GovernmentPolicyUpdate {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *GovernmentPolicyUpdate) AddLongitude(v float64) *GovernmentPolicyUpdate {
	_u.mutation.AddLongitude(v)
	return _u
}

// AddMatchIDs adds the "matches" edge to the PolicyMatch entity by IDs.
func (_u *GovernmentPolicyUpdate) AddMatchIDs(ids ...uuid.UUID) *GovernmentPolicyUpdate {
	_u.mutation.AddMatchIDs(ids...)
	return _u
}

// AddMatches adds the "matches" edges to the PolicyMatch entity.
func (_u *GovernmentPolicyUpdate) AddMatches(v ...*PolicyMatch) *GovernmentPolicyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMatchIDs(ids...)
}

// Mutation returns the GovernmentPolicyMutation object of the builder.
func (_u *GovernmentPolicyUpdate) Mutation() *GovernmentPolicyMutation {
	return _u.mutation
}

// ClearMatches clears all "matches" edges to the PolicyMatch entity.
func (_u *GovernmentPolicyUpdate) ClearMatches() *GovernmentPolicyUpdate {
	_u.mutation.ClearMatches()
	return _u
}

// RemoveMatchIDs removes the "matches" edge to PolicyMatch entities by IDs.
func (_u *GovernmentPolicyUpdate) RemoveMatchIDs(ids ...uuid.UUID) *GovernmentPolicyUpdate {
	_u.mutation.RemoveMatchIDs(ids...)
	return _u
}

// RemoveMatches removes "matches" edges to PolicyMatch entities.
func (_u *GovernmentPolicyUpdate) RemoveMatches(v ...*PolicyMatch) *GovernmentPolicyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMatchIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GovernmentPolicyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GovernmentPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GovernmentPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GovernmentPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GovernmentPolicyUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := governmentpolicy.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "GovernmentPolicy.title": %w`, err)}
		}
	}
	return nil
}

func (_u *GovernmentPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(governmentpolicy.Table, governmentpolicy.Columns, sqlgraph.NewFieldSpec(governmentpolicy.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(governmentpolicy.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(governmentpolicy.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.RegionCode(); ok {
		_spec.SetField(governmentpolicy.FieldRegionCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRegionCode(); ok {
		_spec.AddField(governmentpolicy.FieldRegionCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(governmentpolicy.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(governmentpolicy.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(governmentpolicy.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(governmentpolicy.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(governmentpolicy.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(governmentpolicy.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(governmentpolicy.FieldLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.MatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   governmentpolicy.MatchesTable,
			Columns: []string{governmentpolicy.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMatchesIDs(); len(nodes) > 0 && !_u.mutation.MatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   governmentpolicy.MatchesTable,
			Columns: []string{governmentpolicy.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   governmentpolicy.MatchesTable,
			Columns: []string{governmentpolicy.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{governmentpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GovernmentPolicyUpdateOne is the builder for updating a single GovernmentPolicy entity.
type GovernmentPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GovernmentPolicyMutation
}

// SetTitle sets the "title" field.
func (_u *GovernmentPolicyUpdateOne) SetTitle(v string) *GovernmentPolicyUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *GovernmentPolicyUpdateOne) SetNillableTitle(v *string) *GovernmentPolicyUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GovernmentPolicyUpdateOne) SetDescription(v string) *GovernmentPolicyUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GovernmentPolicyUpdateOne) SetNillableDescription(v *string) *GovernmentPolicyUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetRegionCode sets the "region_code" field.
func (_u *GovernmentPolicyUpdateOne) SetRegionCode(v int) *GovernmentPolicyUpdateOne {
	_u.mutation.ResetRegionCode()
	_u.mutation.SetRegionCode(v)
	return _u
}

// SetNillableRegionCode sets the "region_code" field if the given value is not nil.
func (_u *GovernmentPolicyUpdateOne) SetNillableRegionCode(v *int) *GovernmentPolicyUpdateOne {
	if v != nil {
		_u.SetRegionCode(*v)
	}
	return _u
}

// AddRegionCode adds value to the "region_code" field.
func (_u *GovernmentPolicyUpdateOne) AddRegionCode(v int) *GovernmentPolicyUpdateOne {
	_u.mutation.AddRegionCode(v)
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *GovernmentPolicyUpdateOne) SetStartDate(v time.Time) *GovernmentPolicyUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *GovernmentPolicyUpdateOne) SetNillableStartDate(v *time.Time) *GovernmentPolicyUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *GovernmentPolicyUpdateOne) SetEndDate(v time.Time) *GovernmentPolicyUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *GovernmentPolicyUpdateOne) SetNillableEndDate(v *time.Time) *GovernmentPolicyUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *GovernmentPolicyUpdateOne) SetAddress(v string) *GovernmentPolicyUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *GovernmentPolicyUpdateOne) SetNillableAddress(v *string) *GovernmentPolicyUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *GovernmentPolicyUpdateOne) SetLatitude(v float64) *GovernmentPolicyUpdateOne {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *GovernmentPolicyUpdateOne) SetNillableLatitude(v *float64) *GovernmentPolicyUpdateOne {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *GovernmentPolicyUpdateOne) AddLatitude(v float64) *GovernmentPolicyUpdateOne {
	_u.mutation.AddLatitude(v)
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *GovernmentPolicyUpdateOne) SetLongitude(v float64) *GovernmentPolicyUpdateOne {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *GovernmentPolicyUpdateOne) SetNillableLongitude(v *float64) *GovernmentPolicyUpdateOne {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *GovernmentPolicyUpdateOne) AddLongitude(v float64) *GovernmentPolicyUpdateOne {
	_u.mutation.AddLongitude(v)
	return _u
}

// AddMatchIDs adds the "matches" edge to the PolicyMatch entity by IDs.
func (_u *GovernmentPolicyUpdateOne) AddMatchIDs(ids ...uuid.UUID) *GovernmentPolicyUpdateOne {
	_u.mutation.AddMatchIDs(ids...)
	return _u
}

// AddMatches adds the "matches" edges to the PolicyMatch entity.
func (_u *GovernmentPolicyUpdateOne) AddMatches(v ...*PolicyMatch) *GovernmentPolicyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMatchIDs(ids...)
}

// Mutation returns the GovernmentPolicyMutation object of the builder.
func (_u *GovernmentPolicyUpdateOne) Mutation() *GovernmentPolicyMutation {
	return _u.mutation
}

// ClearMatches clears all "matches" edges to the PolicyMatch entity.
func (_u *GovernmentPolicyUpdateOne) ClearMatches() *GovernmentPolicyUpdateOne {
	_u.mutation.ClearMatches()
	return _u
}

// RemoveMatchIDs removes the "matches" edge to PolicyMatch entities by IDs.
func (_u *GovernmentPolicyUpdateOne) RemoveMatchIDs(ids ...uuid.UUID) *GovernmentPolicyUpdateOne {
	_u.mutation.RemoveMatchIDs(ids...)
	return _u
}

// RemoveMatches removes "matches" edges to PolicyMatch entities.
func (_u *GovernmentPolicyUpdateOne) RemoveMatches(v ...*PolicyMatch) *GovernmentPolicyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMatchIDs(ids...)
}

// Where appends a list predicates to the GovernmentPolicyUpdate builder.
func (_u *GovernmentPolicyUpdateOne) Where(ps ...predicate.GovernmentPolicy) *GovernmentPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GovernmentPolicyUpdateOne) Select(field string, fields ...string) *GovernmentPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GovernmentPolicy entity.
func (_u *GovernmentPolicyUpdateOne) Save(ctx context.Context) (*GovernmentPolicy, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GovernmentPolicyUpdateOne) SaveX(ctx context.Context) *GovernmentPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GovernmentPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GovernmentPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GovernmentPolicyUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := governmentpolicy.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "GovernmentPolicy.title": %w`, err)}
		}
	}
	return nil
}

func (_u *GovernmentPolicyUpdateOne) sqlSave(ctx context.Context) (_node *GovernmentPolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(governmentpolicy.Table, governmentpolicy.Columns, sqlgraph.NewFieldSpec(governmentpolicy.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GovernmentPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, governmentpolicy.FieldID)
		for _, f := range fields {
			if !governmentpolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != governmentpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(governmentpolicy.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(governmentpolicy.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.RegionCode(); ok {
		_spec.SetField(governmentpolicy.FieldRegionCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRegionCode(); ok {
		_spec.AddField(governmentpolicy.FieldRegionCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(governmentpolicy.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(governmentpolicy.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(governmentpolicy.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(governmentpolicy.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(governmentpolicy.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(governmentpolicy.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(governmentpolicy.FieldLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.MatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   governmentpolicy.MatchesTable,
			Columns: []string{governmentpolicy.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMatchesIDs(); len(nodes) > 0 && !_u.mutation.MatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   governmentpolicy.MatchesTable,
			Columns: []string{governmentpolicy.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   governmentpolicy.MatchesTable,
			Columns: []string{governmentpolicy.MatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GovernmentPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{governmentpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
