// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/domain"
	"github.com/janghanul090801/pico-backend/ent/governmentpolicy"
)

// GovernmentPolicy is the model entity for the GovernmentPolicy schema.
type GovernmentPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// RegionCode holds the value of the "region_code" field.
	RegionCode int `json:"region_code,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate time.Time `json:"start_date,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate time.Time `json:"end_date,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Latitude holds the value of the "latitude" field.
	Latitude float64 `json:"latitude,omitempty"`
	// Longitude holds the value of the "longitude" field.
	Longitude float64 `json:"longitude,omitempty"`
	// Condition holds the value of the "condition" field.
	Condition domain.PolicyCondition `json:"condition,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GovernmentPolicyQuery when eager-loading is set.
	Edges        GovernmentPolicyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GovernmentPolicyEdges holds the relations/edges for other nodes in the graph.
type GovernmentPolicyEdges struct {
	// Matches holds the value of the matches edge.
	Matches []*PolicyMatch `json:"matches,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MatchesOrErr returns the Matches value or an error if the edge
// was not loaded in eager-loading.
func (e GovernmentPolicyEdges) MatchesOrErr() ([]*PolicyMatch, error) {
	if e.loadedTypes[0] {
		return e.Matches, nil
	}
	return nil, &NotLoadedError{edge: "matches"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GovernmentPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case governmentpolicy.FieldCondition:
			values[i] = new([]byte)
		case governmentpolicy.FieldLatitude, governmentpolicy.FieldLongitude:
			values[i] = new(sql.NullFloat64)
		case governmentpolicy.FieldRegionCode:
			values[i] = new(sql.NullInt64)
		case governmentpolicy.FieldTitle, governmentpolicy.FieldDescription, governmentpolicy.FieldAddress:
			values[i] = new(sql.NullString)
		case governmentpolicy.FieldStartDate, governmentpolicy.FieldEndDate:
			values[i] = new(sql.NullTime)
		case governmentpolicy.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GovernmentPolicy fields.
func (_m *GovernmentPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case governmentpolicy.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case governmentpolicy.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case governmentpolicy.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case governmentpolicy.FieldRegionCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field region_code", values[i])
			} else if value.Valid {
				_m.RegionCode = int(value.Int64)
			}
		case governmentpolicy.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = value.Time
			}
		case governmentpolicy.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				_m.EndDate = value.Time
			}
		case governmentpolicy.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case governmentpolicy.FieldLatitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field latitude", values[i])
			} else if value.Valid {
				_m.Latitude = value.Float64
			}
		case governmentpolicy.FieldLongitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field longitude", values[i])
			} else if value.Valid {
				_m.Longitude = value.Float64
			}
		case governmentpolicy.FieldCondition:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field condition", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Condition); err != nil {
					return fmt.Errorf("unmarshal field condition: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GovernmentPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *GovernmentPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMatches queries the "matches" edge of the GovernmentPolicy entity.
func (_m *GovernmentPolicy) QueryMatches() *PolicyMatchQuery {
	return NewGovernmentPolicyClient(_m.config).QueryMatches(_m)
}

// Update returns a builder for updating this GovernmentPolicy.
// Note that you need to call GovernmentPolicy.Unwrap() before calling this method if this GovernmentPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GovernmentPolicy) Update() *GovernmentPolicyUpdateOne {
	return NewGovernmentPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GovernmentPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GovernmentPolicy) Unwrap() *GovernmentPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GovernmentPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GovernmentPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("GovernmentPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("region_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.RegionCode))
	builder.WriteString(", ")
	builder.WriteString("start_date=")
	builder.WriteString(_m.StartDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("end_date=")
	builder.WriteString(_m.EndDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("latitude=")
	builder.WriteString(fmt.Sprintf("%v", _m.Latitude))
	builder.WriteString(", ")
	builder.WriteString("longitude=")
	builder.WriteString(fmt.Sprintf("%v", _m.Longitude))
	builder.WriteString(", ")
	builder.WriteString("condition=")
	builder.WriteString(fmt.Sprintf("%v", _m.Condition))
	builder.WriteByte(')')
	return builder.String()
}

// GovernmentPolicies is a parsable slice of GovernmentPolicy.
type GovernmentPolicies []*GovernmentPolicy
