// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/ent/notification"
	"github.com/janghanul090801/pico-backend/ent/predicate"
	"github.com/janghanul090801/pico-backend/ent/user"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *NotificationUpdate) SetType(v int) *NotificationUpdate {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableType(v *int) *NotificationUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *NotificationUpdate) AddType(v int) *NotificationUpdate {
	_u.mutation.AddType(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *NotificationUpdate) SetMessage(v string) *NotificationUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableMessage(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *NotificationUpdate) SetMetadata(v map[string]interface{}) *NotificationUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *NotificationUpdate) ClearMetadata() *NotificationUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetIsRead sets the "is_read" field.
func (_u *NotificationUpdate) SetIsRead(v bool) *NotificationUpdate {
	_u.mutation.SetIsRead(v)
	return _u
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableIsRead(v *bool) *NotificationUpdate {
	if v != nil {
		_u.SetIsRead(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NotificationUpdate) SetCreatedAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableCreatedAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetReceiverID sets the "receiver" edge to the User entity by ID.
func (_u *NotificationUpdate) SetReceiverID(id uuid.UUID) *NotificationUpdate {
	_u.mutation.SetReceiverID(id)
	return _u
}

// SetReceiver sets the "receiver" edge to the User entity.
func (_u *NotificationUpdate) SetReceiver(v *User) *NotificationUpdate {
	return _u.SetReceiverID(v.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// ClearReceiver clears the "receiver" edge to the User entity.
func (_u *NotificationUpdate) ClearReceiver() *NotificationUpdate {
	_u.mutation.ClearReceiver()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdate) check() error {
	if _u.mutation.ReceiverCleared() && len(_u.mutation.ReceiverIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Notification.receiver"`)
	}
	return nil
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(notification.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(notification.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(notification.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(notification.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReceiverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.ReceiverTable,
			Columns: []string{notification.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.ReceiverTable,
			Columns: []string{notification.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetType sets the "type" field.
func (_u *NotificationUpdateOne) SetType(v int) *NotificationUpdateOne {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableType(v *int) *NotificationUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *NotificationUpdateOne) AddType(v int) *NotificationUpdateOne {
	_u.mutation.AddType(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *NotificationUpdateOne) SetMessage(v string) *NotificationUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableMessage(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *NotificationUpdateOne) SetMetadata(v map[string]interface{}) *NotificationUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *NotificationUpdateOne) ClearMetadata() *NotificationUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetIsRead sets the "is_read" field.
func (_u *NotificationUpdateOne) SetIsRead(v bool) *NotificationUpdateOne {
	_u.mutation.SetIsRead(v)
	return _u
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableIsRead(v *bool) *NotificationUpdateOne {
	if v != nil {
		_u.SetIsRead(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NotificationUpdateOne) SetCreatedAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableCreatedAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetReceiverID sets the "receiver" edge to the User entity by ID.
func (_u *NotificationUpdateOne) SetReceiverID(id uuid.UUID) *NotificationUpdateOne {
	_u.mutation.SetReceiverID(id)
	return _u
}

// SetReceiver sets the "receiver" edge to the User entity.
func (_u *NotificationUpdateOne) SetReceiver(v *User) *NotificationUpdateOne {
	return _u.SetReceiverID(v.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// ClearReceiver clears the "receiver" edge to the User entity.
func (_u *NotificationUpdateOne) ClearReceiver() *NotificationUpdateOne {
	_u.mutation.ClearReceiver()
	return _u
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdateOne) check() error {
	if _u.mutation.ReceiverCleared() && len(_u.mutation.ReceiverIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Notification.receiver"`)
	}
	return nil
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(notification.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(notification.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(notification.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(notification.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReceiverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.ReceiverTable,
			Columns: []string{notification.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReceiverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.ReceiverTable,
			Columns: []string{notification.ReceiverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
