// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/ent/governmentpolicy"
	"github.com/janghanul090801/pico-backend/ent/policymatch"
	"github.com/janghanul090801/pico-backend/ent/user"
)

// PolicyMatch is the model entity for the PolicyMatch schema.
type PolicyMatch struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Match holds the value of the "match" field.
	Match policymatch.Match `json:"match,omitempty"`
	// Probability holds the value of the "probability" field.
	Probability *int `json:"probability,omitempty"`
	// Comment holds the value of the "comment" field.
	Comment *string `json:"comment,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PolicyMatchQuery when eager-loading is set.
	Edges                     PolicyMatchEdges `json:"edges"`
	government_policy_matches *uuid.UUID
	user_policy_matches       *uuid.UUID
	selectValues              sql.SelectValues
}

// PolicyMatchEdges holds the relations/edges for other nodes in the graph.
type PolicyMatchEdges struct {
	// Policy holds the value of the policy edge.
	Policy *GovernmentPolicy `json:"policy,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PolicyOrErr returns the Policy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PolicyMatchEdges) PolicyOrErr() (*GovernmentPolicy, error) {
	if e.Policy != nil {
		return e.Policy, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: governmentpolicy.Label}
	}
	return nil, &NotLoadedError{edge: "policy"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PolicyMatchEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PolicyMatch) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case policymatch.FieldProbability:
			values[i] = new(sql.NullInt64)
		case policymatch.FieldMatch, policymatch.FieldComment:
			values[i] = new(sql.NullString)
		case policymatch.FieldID:
			values[i] = new(uuid.UUID)
		case policymatch.ForeignKeys[0]: // government_policy_matches
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case policymatch.ForeignKeys[1]: // user_policy_matches
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PolicyMatch fields.
func (_m *PolicyMatch) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case policymatch.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case policymatch.FieldMatch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match", values[i])
			} else if value.Valid {
				_m.Match = policymatch.Match(value.String)
			}
		case policymatch.FieldProbability:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field probability", values[i])
			} else if value.Valid {
				_m.Probability = new(int)
				*_m.Probability = int(value.Int64)
			}
		case policymatch.FieldComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comment", values[i])
			} else if value.Valid {
				_m.Comment = new(string)
				*_m.Comment = value.String
			}
		case policymatch.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field government_policy_matches", values[i])
			} else if value.Valid {
				_m.government_policy_matches = new(uuid.UUID)
				*_m.government_policy_matches = *value.S.(*uuid.UUID)
			}
		case policymatch.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_policy_matches", values[i])
			} else if value.Valid {
				_m.user_policy_matches = new(uuid.UUID)
				*_m.user_policy_matches = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PolicyMatch.
// This includes values selected through modifiers, order, etc.
func (_m *PolicyMatch) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPolicy queries the "policy" edge of the PolicyMatch entity.
func (_m *PolicyMatch) QueryPolicy() *GovernmentPolicyQuery {
	return NewPolicyMatchClient(_m.config).QueryPolicy(_m)
}

// QueryUser queries the "user" edge of the PolicyMatch entity.
func (_m *PolicyMatch) QueryUser() *UserQuery {
	return NewPolicyMatchClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this PolicyMatch.
// Note that you need to call PolicyMatch.Unwrap() before calling this method if this PolicyMatch
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PolicyMatch) Update() *PolicyMatchUpdateOne {
	return NewPolicyMatchClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PolicyMatch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PolicyMatch) Unwrap() *PolicyMatch {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PolicyMatch is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PolicyMatch) String() string {
	var builder strings.Builder
	builder.WriteString("PolicyMatch(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("match=")
	builder.WriteString(fmt.Sprintf("%v", _m.Match))
	builder.WriteString(", ")
	if v := _m.Probability; v != nil {
		builder.WriteString("probability=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Comment; v != nil {
		builder.WriteString("comment=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// PolicyMatches is a parsable slice of PolicyMatch.
type PolicyMatches []*PolicyMatch
