// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/ent/governmentpolicy"
	"github.com/janghanul090801/pico-backend/ent/policymatch"
	"github.com/janghanul090801/pico-backend/ent/predicate"
	"github.com/janghanul090801/pico-backend/ent/user"
)

// PolicyMatchUpdate is the builder for updating PolicyMatch entities.
type PolicyMatchUpdate struct {
	config
	hooks    []Hook
	mutation *PolicyMatchMutation
}

// Where appends a list predicates to the PolicyMatchUpdate builder.
func (_u *PolicyMatchUpdate) Where(ps ...predicate.PolicyMatch) *PolicyMatchUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMatch sets the "match" field.
func (_u *PolicyMatchUpdate) SetMatch(v policymatch.Match) *PolicyMatchUpdate {
	_u.mutation.SetMatch(v)
	return _u
}

// SetNillableMatch sets the "match" field if the given value is not nil.
func (_u *PolicyMatchUpdate) SetNillableMatch(v *policymatch.Match) *PolicyMatchUpdate {
	if v != nil {
		_u.SetMatch(*v)
	}
	return _u
}

// SetProbability sets the "probability" field.
func (_u *PolicyMatchUpdate) SetProbability(v int) *PolicyMatchUpdate {
	_u.mutation.ResetProbability()
	_u.mutation.SetProbability(v)
	return _u
}

// SetNillableProbability sets the "probability" field if the given value is not nil.
func (_u *PolicyMatchUpdate) SetNillableProbability(v *int) *PolicyMatchUpdate {
	if v != nil {
		_u.SetProbability(*v)
	}
	return _u
}

// AddProbability adds value to the "probability" field.
func (_u *PolicyMatchUpdate) AddProbability(v int) *PolicyMatchUpdate {
	_u.mutation.AddProbability(v)
	return _u
}

// ClearProbability clears the value of the "probability" field.
func (_u *PolicyMatchUpdate) ClearProbability() *PolicyMatchUpdate {
	_u.mutation.ClearProbability()
	return _u
}

// SetComment sets the "comment" field.
func (_u *PolicyMatchUpdate) SetComment(v string) *PolicyMatchUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *PolicyMatchUpdate) SetNillableComment(v *string) *PolicyMatchUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *PolicyMatchUpdate) ClearComment() *PolicyMatchUpdate {
	_u.mutation.ClearComment()
	return _u
}

// SetPolicyID sets the "policy" edge to the GovernmentPolicy entity by ID.
func (_u *PolicyMatchUpdate) SetPolicyID(id uuid.UUID) *PolicyMatchUpdate {
	_u.mutation.SetPolicyID(id)
	return _u
}

// SetPolicy sets the "policy" edge to the GovernmentPolicy entity.
func (_u *PolicyMatchUpdate) SetPolicy(v *GovernmentPolicy) *PolicyMatchUpdate {
	return _u.SetPolicyID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PolicyMatchUpdate) SetUserID(id uuid.UUID) *PolicyMatchUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PolicyMatchUpdate) SetUser(v *User) *PolicyMatchUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PolicyMatchMutation object of the builder.
func (_u *PolicyMatchUpdate) Mutation() *PolicyMatchMutation {
	return _u.mutation
}

// ClearPolicy clears the "policy" edge to the GovernmentPolicy entity.
func (_u *PolicyMatchUpdate) ClearPolicy() *PolicyMatchUpdate {
	_u.mutation.ClearPolicy()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PolicyMatchUpdate) ClearUser() *PolicyMatchUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PolicyMatchUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PolicyMatchUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PolicyMatchUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PolicyMatchUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PolicyMatchUpdate) check() error {
	if v, ok := _u.mutation.Match(); ok {
		if err := policymatch.MatchValidator(v); err != nil {
			return &ValidationError{Name: "match", err: fmt.Errorf(`ent: validator failed for field "PolicyMatch.match": %w`, err)}
		}
	}
	if _u.mutation.PolicyCleared() && len(_u.mutation.PolicyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PolicyMatch.policy"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PolicyMatch.user"`)
	}
	return nil
}

func (_u *PolicyMatchUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(policymatch.Table, policymatch.Columns, sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Match(); ok {
		_spec.SetField(policymatch.FieldMatch, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Probability(); ok {
		_spec.SetField(policymatch.FieldProbability, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProbability(); ok {
		_spec.AddField(policymatch.FieldProbability, field.TypeInt, value)
	}
	if _u.mutation.ProbabilityCleared() {
		_spec.ClearField(policymatch.FieldProbability, field.TypeInt)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(policymatch.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(policymatch.FieldComment, field.TypeString)
	}
	if _u.mutation.PolicyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policymatch.PolicyTable,
			Columns: []string{policymatch.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(governmentpolicy.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PolicyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policymatch.PolicyTable,
			Columns: []string{policymatch.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(governmentpolicy.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policymatch.UserTable,
			Columns: []string{policymatch.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policymatch.UserTable,
			Columns: []string{policymatch.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{policymatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PolicyMatchUpdateOne is the builder for updating a single PolicyMatch entity.
type PolicyMatchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PolicyMatchMutation
}

// SetMatch sets the "match" field.
func (_u *PolicyMatchUpdateOne) SetMatch(v policymatch.Match) *PolicyMatchUpdateOne {
	_u.mutation.SetMatch(v)
	return _u
}

// SetNillableMatch sets the "match" field if the given value is not nil.
func (_u *PolicyMatchUpdateOne) SetNillableMatch(v *policymatch.Match) *PolicyMatchUpdateOne {
	if v != nil {
		_u.SetMatch(*v)
	}
	return _u
}

// SetProbability sets the "probability" field.
func (_u *PolicyMatchUpdateOne) SetProbability(v int) *PolicyMatchUpdateOne {
	_u.mutation.ResetProbability()
	_u.mutation.SetProbability(v)
	return _u
}

// SetNillableProbability sets the "probability" field if the given value is not nil.
func (_u *PolicyMatchUpdateOne) SetNillableProbability(v *int) *PolicyMatchUpdateOne {
	if v != nil {
		_u.SetProbability(*v)
	}
	return _u
}

// AddProbability adds value to the "probability" field.
func (_u *PolicyMatchUpdateOne) AddProbability(v int) *PolicyMatchUpdateOne {
	_u.mutation.AddProbability(v)
	return _u
}

// ClearProbability clears the value of the "probability" field.
func (_u *PolicyMatchUpdateOne) ClearProbability() *PolicyMatchUpdateOne {
	_u.mutation.ClearProbability()
	return _u
}

// SetComment sets the "comment" field.
func (_u *PolicyMatchUpdateOne) SetComment(v string) *PolicyMatchUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *PolicyMatchUpdateOne) SetNillableComment(v *string) *PolicyMatchUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *PolicyMatchUpdateOne) ClearComment() *PolicyMatchUpdateOne {
	_u.mutation.ClearComment()
	return _u
}

// SetPolicyID sets the "policy" edge to the GovernmentPolicy entity by ID.
func (_u *PolicyMatchUpdateOne) SetPolicyID(id uuid.UUID) *PolicyMatchUpdateOne {
	_u.mutation.SetPolicyID(id)
	return _u
}

// SetPolicy sets the "policy" edge to the GovernmentPolicy entity.
func (_u *PolicyMatchUpdateOne) SetPolicy(v *GovernmentPolicy) *PolicyMatchUpdateOne {
	return _u.SetPolicyID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PolicyMatchUpdateOne) SetUserID(id uuid.UUID) *PolicyMatchUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PolicyMatchUpdateOne) SetUser(v *User) *PolicyMatchUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PolicyMatchMutation object of the builder.
func (_u *PolicyMatchUpdateOne) Mutation() *PolicyMatchMutation {
	return _u.mutation
}

// ClearPolicy clears the "policy" edge to the GovernmentPolicy entity.
func (_u *PolicyMatchUpdateOne) ClearPolicy() *PolicyMatchUpdateOne {
	_u.mutation.ClearPolicy()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PolicyMatchUpdateOne) ClearUser() *PolicyMatchUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PolicyMatchUpdate builder.
func (_u *PolicyMatchUpdateOne) Where(ps ...predicate.PolicyMatch) *PolicyMatchUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PolicyMatchUpdateOne) Select(field string, fields ...string) *PolicyMatchUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PolicyMatch entity.
func (_u *PolicyMatchUpdateOne) Save(ctx context.Context) (*PolicyMatch, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PolicyMatchUpdateOne) SaveX(ctx context.Context) *PolicyMatch {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PolicyMatchUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PolicyMatchUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PolicyMatchUpdateOne) check() error {
	if v, ok := _u.mutation.Match(); ok {
		if err := policymatch.MatchValidator(v); err != nil {
			return &ValidationError{Name: "match", err: fmt.Errorf(`ent: validator failed for field "PolicyMatch.match": %w`, err)}
		}
	}
	if _u.mutation.PolicyCleared() && len(_u.mutation.PolicyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PolicyMatch.policy"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PolicyMatch.user"`)
	}
	return nil
}

func (_u *PolicyMatchUpdateOne) sqlSave(ctx context.Context) (_node *PolicyMatch, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(policymatch.Table, policymatch.Columns, sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PolicyMatch.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, policymatch.FieldID)
		for _, f := range fields {
			if !policymatch.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != policymatch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Match(); ok {
		_spec.SetField(policymatch.FieldMatch, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Probability(); ok {
		_spec.SetField(policymatch.FieldProbability, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProbability(); ok {
		_spec.AddField(policymatch.FieldProbability, field.TypeInt, value)
	}
	if _u.mutation.ProbabilityCleared() {
		_spec.ClearField(policymatch.FieldProbability, field.TypeInt)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(policymatch.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(policymatch.FieldComment, field.TypeString)
	}
	if _u.mutation.PolicyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policymatch.PolicyTable,
			Columns: []string{policymatch.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(governmentpolicy.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PolicyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policymatch.PolicyTable,
			Columns: []string{policymatch.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(governmentpolicy.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policymatch.UserTable,
			Columns: []string{policymatch.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policymatch.UserTable,
			Columns: []string{policymatch.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PolicyMatch{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{policymatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
