// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/ent/governmentpolicy"
	"github.com/janghanul090801/pico-backend/ent/policymatch"
	"github.com/janghanul090801/pico-backend/ent/user"
)

// PolicyMatchCreate is the builder for creating a PolicyMatch entity.
type PolicyMatchCreate struct {
	config
	mutation *PolicyMatchMutation
	hooks    []Hook
}

// SetMatch sets the "match" field.
func (_c *PolicyMatchCreate) SetMatch(v policymatch.Match) *PolicyMatchCreate {
	_c.mutation.SetMatch(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PolicyMatchCreate) SetID(v uuid.UUID) *PolicyMatchCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PolicyMatchCreate) SetNillableID(v *uuid.UUID) *PolicyMatchCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPolicyID sets the "policy" edge to the GovernmentPolicy entity by ID.
func (_c *PolicyMatchCreate) SetPolicyID(id uuid.UUID) *PolicyMatchCreate {
	_c.mutation.SetPolicyID(id)
	return _c
}

// SetPolicy sets the "policy" edge to the GovernmentPolicy entity.
func (_c *PolicyMatchCreate) SetPolicy(v *GovernmentPolicy) *PolicyMatchCreate {
	return _c.SetPolicyID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *PolicyMatchCreate) SetUserID(id uuid.UUID) *PolicyMatchCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PolicyMatchCreate) SetUser(v *User) *PolicyMatchCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PolicyMatchMutation object of the builder.
func (_c *PolicyMatchCreate) Mutation() *PolicyMatchMutation {
	return _c.mutation
}

// Save creates the PolicyMatch in the database.
func (_c *PolicyMatchCreate) Save(ctx context.Context) (*PolicyMatch, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PolicyMatchCreate) SaveX(ctx context.Context) *PolicyMatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PolicyMatchCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PolicyMatchCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PolicyMatchCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := policymatch.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PolicyMatchCreate) check() error {
	if _, ok := _c.mutation.Match(); !ok {
		return &ValidationError{Name: "match", err: errors.New(`ent: missing required field "PolicyMatch.match"`)}
	}
	if v, ok := _c.mutation.Match(); ok {
		if err := policymatch.MatchValidator(v); err != nil {
			return &ValidationError{Name: "match", err: fmt.Errorf(`ent: validator failed for field "PolicyMatch.match": %w`, err)}
		}
	}
	if len(_c.mutation.PolicyIDs()) == 0 {
		return &ValidationError{Name: "policy", err: errors.New(`ent: missing required edge "PolicyMatch.policy"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PolicyMatch.user"`)}
	}
	return nil
}

func (_c *PolicyMatchCreate) sqlSave(ctx context.Context) (*PolicyMatch, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PolicyMatchCreate) createSpec() (*PolicyMatch, *sqlgraph.CreateSpec) {
	var (
		_node = &PolicyMatch{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(policymatch.Table, sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Match(); ok {
		_spec.SetField(policymatch.FieldMatch, field.TypeEnum, value)
		_node.Match = value
	}
	if nodes := _c.mutation.PolicyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policymatch.PolicyTable,
			Columns: []string{policymatch.PolicyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(governmentpolicy.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.government_policy_matches = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   policymatch.UserTable,
			Columns: []string{policymatch.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_policy_matches = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PolicyMatchCreateBulk is the builder for creating many PolicyMatch entities in bulk.
type PolicyMatchCreateBulk struct {
	config
	err      error
	builders []*PolicyMatchCreate
}

// Save creates the PolicyMatch entities in the database.
func (_c *PolicyMatchCreateBulk) Save(ctx context.Context) ([]*PolicyMatch, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PolicyMatch, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PolicyMatchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PolicyMatchCreateBulk) SaveX(ctx context.Context) []*PolicyMatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PolicyMatchCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PolicyMatchCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
