// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/domain"
	"github.com/janghanul090801/pico-backend/ent/favorite"
	"github.com/janghanul090801/pico-backend/ent/governmentpolicy"
	"github.com/janghanul090801/pico-backend/ent/notification"
	"github.com/janghanul090801/pico-backend/ent/policymatch"
	"github.com/janghanul090801/pico-backend/ent/schema"
	"github.com/janghanul090801/pico-backend/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	favoriteFields := schema.Favorite{}.Fields()
	_ = favoriteFields
	// favoriteDescCreatedAt is the schema descriptor for created_at field.
	favoriteDescCreatedAt := favoriteFields[1].Descriptor()
	// favorite.DefaultCreatedAt holds the default value on creation for the created_at field.
	favorite.DefaultCreatedAt = favoriteDescCreatedAt.Default.(func() time.Time)
	// favoriteDescID is the schema descriptor for id field.
	favoriteDescID := favoriteFields[0].Descriptor()
	// favorite.DefaultID holds the default value on creation for the id field.
	favorite.DefaultID = favoriteDescID.Default.(func() uuid.UUID)
	governmentpolicyFields := schema.GovernmentPolicy{}.Fields()
	_ = governmentpolicyFields
	// governmentpolicyDescTitle is the schema descriptor for title field.
	governmentpolicyDescTitle := governmentpolicyFields[1].Descriptor()
	// governmentpolicy.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	governmentpolicy.TitleValidator = governmentpolicyDescTitle.Validators[0].(func(string) error)
	// governmentpolicyDescCondition is the schema descriptor for condition field.
	governmentpolicyDescCondition := governmentpolicyFields[9].Descriptor()
	// governmentpolicy.DefaultCondition holds the default value on creation for the condition field.
	governmentpolicy.DefaultCondition = governmentpolicyDescCondition.Default.(domain.PolicyCondition)
	// governmentpolicyDescID is the schema descriptor for id field.
	governmentpolicyDescID := governmentpolicyFields[0].Descriptor()
	// governmentpolicy.DefaultID holds the default value on creation for the id field.
	governmentpolicy.DefaultID = governmentpolicyDescID.Default.(func() uuid.UUID)
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescIsRead is the schema descriptor for is_read field.
	notificationDescIsRead := notificationFields[4].Descriptor()
	// notification.DefaultIsRead holds the default value on creation for the is_read field.
	notification.DefaultIsRead = notificationDescIsRead.Default.(bool)
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationFields[5].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(func() time.Time)
	// notificationDescID is the schema descriptor for id field.
	notificationDescID := notificationFields[0].Descriptor()
	// notification.DefaultID holds the default value on creation for the id field.
	notification.DefaultID = notificationDescID.Default.(func() uuid.UUID)
	policymatchFields := schema.PolicyMatch{}.Fields()
	_ = policymatchFields
	// policymatchDescID is the schema descriptor for id field.
	policymatchDescID := policymatchFields[0].Descriptor()
	// policymatch.DefaultID holds the default value on creation for the id field.
	policymatch.DefaultID = policymatchDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescIsStudent is the schema descriptor for is_student field.
	userDescIsStudent := userFields[7].Descriptor()
	// user.DefaultIsStudent holds the default value on creation for the is_student field.
	user.DefaultIsStudent = userDescIsStudent.Default.(bool)
	// userDescIsYouth is the schema descriptor for is_youth field.
	userDescIsYouth := userFields[8].Descriptor()
	// user.DefaultIsYouth holds the default value on creation for the is_youth field.
	user.DefaultIsYouth = userDescIsYouth.Default.(bool)
	// userDescIsPregnant is the schema descriptor for is_pregnant field.
	userDescIsPregnant := userFields[9].Descriptor()
	// user.DefaultIsPregnant holds the default value on creation for the is_pregnant field.
	user.DefaultIsPregnant = userDescIsPregnant.Default.(bool)
	// userDescIsBusiness is the schema descriptor for is_business field.
	userDescIsBusiness := userFields[10].Descriptor()
	// user.DefaultIsBusiness holds the default value on creation for the is_business field.
	user.DefaultIsBusiness = userDescIsBusiness.Default.(bool)
	// userDescIsForeign is the schema descriptor for is_foreign field.
	userDescIsForeign := userFields[11].Descriptor()
	// user.DefaultIsForeign holds the default value on creation for the is_foreign field.
	user.DefaultIsForeign = userDescIsForeign.Default.(bool)
	// userDescIsDisabled is the schema descriptor for is_disabled field.
	userDescIsDisabled := userFields[12].Descriptor()
	// user.DefaultIsDisabled holds the default value on creation for the is_disabled field.
	user.DefaultIsDisabled = userDescIsDisabled.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[14].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
