// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// RegionCode holds the value of the "region_code" field.
	RegionCode int `json:"region_code,omitempty"`
	// Gender holds the value of the "gender" field.
	Gender user.Gender `json:"gender,omitempty"`
	// IsStudent holds the value of the "is_student" field.
	IsStudent bool `json:"is_student,omitempty"`
	// IsYouth holds the value of the "is_youth" field.
	IsYouth bool `json:"is_youth,omitempty"`
	// IsPregnant holds the value of the "is_pregnant" field.
	IsPregnant bool `json:"is_pregnant,omitempty"`
	// IsBusiness holds the value of the "is_business" field.
	IsBusiness bool `json:"is_business,omitempty"`
	// IsForeign holds the value of the "is_foreign" field.
	IsForeign bool `json:"is_foreign,omitempty"`
	// IsDisabled holds the value of the "is_disabled" field.
	IsDisabled bool `json:"is_disabled,omitempty"`
	// Interests holds the value of the "interests" field.
	Interests []string `json:"interests,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// PolicyMatches holds the value of the policy_matches edge.
	PolicyMatches []*PolicyMatch `json:"policy_matches,omitempty"`
	// Notifications holds the value of the notifications edge.
	Notifications []*Notification `json:"notifications,omitempty"`
	// Favorites holds the value of the favorites edge.
	Favorites []*Favorite `json:"favorites,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PolicyMatchesOrErr returns the PolicyMatches value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) PolicyMatchesOrErr() ([]*PolicyMatch, error) {
	if e.loadedTypes[0] {
		return e.PolicyMatches, nil
	}
	return nil, &NotLoadedError{edge: "policy_matches"}
}

// NotificationsOrErr returns the Notifications value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) NotificationsOrErr() ([]*Notification, error) {
	if e.loadedTypes[1] {
		return e.Notifications, nil
	}
	return nil, &NotLoadedError{edge: "notifications"}
}

// FavoritesOrErr returns the Favorites value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FavoritesOrErr() ([]*Favorite, error) {
	if e.loadedTypes[2] {
		return e.Favorites, nil
	}
	return nil, &NotLoadedError{edge: "favorites"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldInterests:
			values[i] = new([]byte)
		case user.FieldIsStudent, user.FieldIsYouth, user.FieldIsPregnant, user.FieldIsBusiness, user.FieldIsForeign, user.FieldIsDisabled:
			values[i] = new(sql.NullBool)
		case user.FieldAge, user.FieldRegionCode:
			values[i] = new(sql.NullInt64)
		case user.FieldName, user.FieldEmail, user.FieldPassword, user.FieldGender:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case user.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case user.FieldAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value.Valid {
				_m.Age = int(value.Int64)
			}
		case user.FieldRegionCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field region_code", values[i])
			} else if value.Valid {
				_m.RegionCode = int(value.Int64)
			}
		case user.FieldGender:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gender", values[i])
			} else if value.Valid {
				_m.Gender = user.Gender(value.String)
			}
		case user.FieldIsStudent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_student", values[i])
			} else if value.Valid {
				_m.IsStudent = value.Bool
			}
		case user.FieldIsYouth:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_youth", values[i])
			} else if value.Valid {
				_m.IsYouth = value.Bool
			}
		case user.FieldIsPregnant:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_pregnant", values[i])
			} else if value.Valid {
				_m.IsPregnant = value.Bool
			}
		case user.FieldIsBusiness:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_business", values[i])
			} else if value.Valid {
				_m.IsBusiness = value.Bool
			}
		case user.FieldIsForeign:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_foreign", values[i])
			} else if value.Valid {
				_m.IsForeign = value.Bool
			}
		case user.FieldIsDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_disabled", values[i])
			} else if value.Valid {
				_m.IsDisabled = value.Bool
			}
		case user.FieldInterests:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field interests", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Interests); err != nil {
					return fmt.Errorf("unmarshal field interests: %w", err)
				}
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPolicyMatches queries the "policy_matches" edge of the User entity.
func (_m *User) QueryPolicyMatches() *PolicyMatchQuery {
	return NewUserClient(_m.config).QueryPolicyMatches(_m)
}

// QueryNotifications queries the "notifications" edge of the User entity.
func (_m *User) QueryNotifications() *NotificationQuery {
	return NewUserClient(_m.config).QueryNotifications(_m)
}

// QueryFavorites queries the "favorites" edge of the User entity.
func (_m *User) QueryFavorites() *FavoriteQuery {
	return NewUserClient(_m.config).QueryFavorites(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(_m.Password)
	builder.WriteString(", ")
	builder.WriteString("age=")
	builder.WriteString(fmt.Sprintf("%v", _m.Age))
	builder.WriteString(", ")
	builder.WriteString("region_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.RegionCode))
	builder.WriteString(", ")
	builder.WriteString("gender=")
	builder.WriteString(fmt.Sprintf("%v", _m.Gender))
	builder.WriteString(", ")
	builder.WriteString("is_student=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsStudent))
	builder.WriteString(", ")
	builder.WriteString("is_youth=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsYouth))
	builder.WriteString(", ")
	builder.WriteString("is_pregnant=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPregnant))
	builder.WriteString(", ")
	builder.WriteString("is_business=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsBusiness))
	builder.WriteString(", ")
	builder.WriteString("is_foreign=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsForeign))
	builder.WriteString(", ")
	builder.WriteString("is_disabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDisabled))
	builder.WriteString(", ")
	builder.WriteString("interests=")
	builder.WriteString(fmt.Sprintf("%v", _m.Interests))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
