// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/ent/favorite"
	"github.com/janghanul090801/pico-backend/ent/notification"
	"github.com/janghanul090801/pico-backend/ent/policymatch"
	"github.com/janghanul090801/pico-backend/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *UserCreate) SetName(v string) *UserCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *UserCreate) SetEmail(v string) *UserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPassword sets the "password" field.
func (_c *UserCreate) SetPassword(v string) *UserCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetAge sets the "age" field.
func (_c *UserCreate) SetAge(v int) *UserCreate {
	_c.mutation.SetAge(v)
	return _c
}

// SetRegionCode sets the "region_code" field.
func (_c *UserCreate) SetRegionCode(v int) *UserCreate {
	_c.mutation.SetRegionCode(v)
	return _c
}

// SetGender sets the "gender" field.
func (_c *UserCreate) SetGender(v user.Gender) *UserCreate {
	_c.mutation.SetGender(v)
	return _c
}

// SetIsStudent sets the "is_student" field.
func (_c *UserCreate) SetIsStudent(v bool) *UserCreate {
	_c.mutation.SetIsStudent(v)
	return _c
}

// SetNillableIsStudent sets the "is_student" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsStudent(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsStudent(*v)
	}
	return _c
}

// SetIsYouth sets the "is_youth" field.
func (_c *UserCreate) SetIsYouth(v bool) *UserCreate {
	_c.mutation.SetIsYouth(v)
	return _c
}

// SetNillableIsYouth sets the "is_youth" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsYouth(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsYouth(*v)
	}
	return _c
}

// SetIsPregnant sets the "is_pregnant" field.
func (_c *UserCreate) SetIsPregnant(v bool) *UserCreate {
	_c.mutation.SetIsPregnant(v)
	return _c
}

// SetNillableIsPregnant sets the "is_pregnant" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsPregnant(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsPregnant(*v)
	}
	return _c
}

// SetIsBusiness sets the "is_business" field.
func (_c *UserCreate) SetIsBusiness(v bool) *UserCreate {
	_c.mutation.SetIsBusiness(v)
	return _c
}

// SetNillableIsBusiness sets the "is_business" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsBusiness(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsBusiness(*v)
	}
	return _c
}

// SetIsForeign sets the "is_foreign" field.
func (_c *UserCreate) SetIsForeign(v bool) *UserCreate {
	_c.mutation.SetIsForeign(v)
	return _c
}

// SetNillableIsForeign sets the "is_foreign" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsForeign(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsForeign(*v)
	}
	return _c
}

// SetIsDisabled sets the "is_disabled" field.
func (_c *UserCreate) SetIsDisabled(v bool) *UserCreate {
	_c.mutation.SetIsDisabled(v)
	return _c
}

// SetNillableIsDisabled sets the "is_disabled" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsDisabled(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsDisabled(*v)
	}
	return _c
}

// SetInterests sets the "interests" field.
func (_c *UserCreate) SetInterests(v []string) *UserCreate {
	_c.mutation.SetInterests(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserCreate) SetID(v uuid.UUID) *UserCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserCreate) SetNillableID(v *uuid.UUID) *UserCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddPolicyMatchIDs adds the "policy_matches" edge to the PolicyMatch entity by IDs.
func (_c *UserCreate) AddPolicyMatchIDs(ids ...uuid.UUID) *UserCreate {
	_c.mutation.AddPolicyMatchIDs(ids...)
	return _c
}

// AddPolicyMatches adds the "policy_matches" edges to the PolicyMatch entity.
func (_c *UserCreate) AddPolicyMatches(v ...*PolicyMatch) *UserCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPolicyMatchIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_c *UserCreate) AddNotificationIDs(ids ...uuid.UUID) *UserCreate {
	_c.mutation.AddNotificationIDs(ids...)
	return _c
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_c *UserCreate) AddNotifications(v ...*Notification) *UserCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNotificationIDs(ids...)
}

// AddFavoriteIDs adds the "favorites" edge to the Favorite entity by IDs.
func (_c *UserCreate) AddFavoriteIDs(ids ...uuid.UUID) *UserCreate {
	_c.mutation.AddFavoriteIDs(ids...)
	return _c
}

// AddFavorites adds the "favorites" edges to the Favorite entity.
func (_c *UserCreate) AddFavorites(v ...*Favorite) *UserCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFavoriteIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.IsStudent(); !ok {
		v := user.DefaultIsStudent
		_c.mutation.SetIsStudent(v)
	}
	if _, ok := _c.mutation.IsYouth(); !ok {
		v := user.DefaultIsYouth
		_c.mutation.SetIsYouth(v)
	}
	if _, ok := _c.mutation.IsPregnant(); !ok {
		v := user.DefaultIsPregnant
		_c.mutation.SetIsPregnant(v)
	}
	if _, ok := _c.mutation.IsBusiness(); !ok {
		v := user.DefaultIsBusiness
		_c.mutation.SetIsBusiness(v)
	}
	if _, ok := _c.mutation.IsForeign(); !ok {
		v := user.DefaultIsForeign
		_c.mutation.SetIsForeign(v)
	}
	if _, ok := _c.mutation.IsDisabled(); !ok {
		v := user.DefaultIsDisabled
		_c.mutation.SetIsDisabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := user.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "User.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "User.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "User.password"`)}
	}
	if v, ok := _c.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Age(); !ok {
		return &ValidationError{Name: "age", err: errors.New(`ent: missing required field "User.age"`)}
	}
	if _, ok := _c.mutation.RegionCode(); !ok {
		return &ValidationError{Name: "region_code", err: errors.New(`ent: missing required field "User.region_code"`)}
	}
	if _, ok := _c.mutation.Gender(); !ok {
		return &ValidationError{Name: "gender", err: errors.New(`ent: missing required field "User.gender"`)}
	}
	if v, ok := _c.mutation.Gender(); ok {
		if err := user.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "User.gender": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsStudent(); !ok {
		return &ValidationError{Name: "is_student", err: errors.New(`ent: missing required field "User.is_student"`)}
	}
	if _, ok := _c.mutation.IsYouth(); !ok {
		return &ValidationError{Name: "is_youth", err: errors.New(`ent: missing required field "User.is_youth"`)}
	}
	if _, ok := _c.mutation.IsPregnant(); !ok {
		return &ValidationError{Name: "is_pregnant", err: errors.New(`ent: missing required field "User.is_pregnant"`)}
	}
	if _, ok := _c.mutation.IsBusiness(); !ok {
		return &ValidationError{Name: "is_business", err: errors.New(`ent: missing required field "User.is_business"`)}
	}
	if _, ok := _c.mutation.IsForeign(); !ok {
		return &ValidationError{Name: "is_foreign", err: errors.New(`ent: missing required field "User.is_foreign"`)}
	}
	if _, ok := _c.mutation.IsDisabled(); !ok {
		return &ValidationError{Name: "is_disabled", err: errors.New(`ent: missing required field "User.is_disabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.Age(); ok {
		_spec.SetField(user.FieldAge, field.TypeInt, value)
		_node.Age = value
	}
	if value, ok := _c.mutation.RegionCode(); ok {
		_spec.SetField(user.FieldRegionCode, field.TypeInt, value)
		_node.RegionCode = value
	}
	if value, ok := _c.mutation.Gender(); ok {
		_spec.SetField(user.FieldGender, field.TypeEnum, value)
		_node.Gender = value
	}
	if value, ok := _c.mutation.IsStudent(); ok {
		_spec.SetField(user.FieldIsStudent, field.TypeBool, value)
		_node.IsStudent = value
	}
	if value, ok := _c.mutation.IsYouth(); ok {
		_spec.SetField(user.FieldIsYouth, field.TypeBool, value)
		_node.IsYouth = value
	}
	if value, ok := _c.mutation.IsPregnant(); ok {
		_spec.SetField(user.FieldIsPregnant, field.TypeBool, value)
		_node.IsPregnant = value
	}
	if value, ok := _c.mutation.IsBusiness(); ok {
		_spec.SetField(user.FieldIsBusiness, field.TypeBool, value)
		_node.IsBusiness = value
	}
	if value, ok := _c.mutation.IsForeign(); ok {
		_spec.SetField(user.FieldIsForeign, field.TypeBool, value)
		_node.IsForeign = value
	}
	if value, ok := _c.mutation.IsDisabled(); ok {
		_spec.SetField(user.FieldIsDisabled, field.TypeBool, value)
		_node.IsDisabled = value
	}
	if value, ok := _c.mutation.Interests(); ok {
		_spec.SetField(user.FieldInterests, field.TypeJSON, value)
		_node.Interests = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PolicyMatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PolicyMatchesTable,
			Columns: []string{user.PolicyMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FavoritesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FavoritesTable,
			Columns: []string{user.FavoritesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(favorite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
