// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/ent/notification"
	"github.com/janghanul090801/pico-backend/ent/policymatch"
	"github.com/janghanul090801/pico-backend/ent/predicate"
	"github.com/janghanul090801/pico-backend/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserUpdate) SetPassword(v string) *UserUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePassword(v *string) *UserUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetAge sets the "age" field.
func (_u *UserUpdate) SetAge(v int) *UserUpdate {
	_u.mutation.ResetAge()
	_u.mutation.SetAge(v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAge(v *int) *UserUpdate {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *UserUpdate) AddAge(v int) *UserUpdate {
	_u.mutation.AddAge(v)
	return _u
}

// SetRegionCode sets the "region_code" field.
func (_u *UserUpdate) SetRegionCode(v int) *UserUpdate {
	_u.mutation.ResetRegionCode()
	_u.mutation.SetRegionCode(v)
	return _u
}

// SetNillableRegionCode sets the "region_code" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRegionCode(v *int) *UserUpdate {
	if v != nil {
		_u.SetRegionCode(*v)
	}
	return _u
}

// AddRegionCode adds value to the "region_code" field.
func (_u *UserUpdate) AddRegionCode(v int) *UserUpdate {
	_u.mutation.AddRegionCode(v)
	return _u
}

// SetGender sets the "gender" field.
func (_u *UserUpdate) SetGender(v user.Gender) *UserUpdate {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGender(v *user.Gender) *UserUpdate {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// SetIsStudent sets the "is_student" field.
func (_u *UserUpdate) SetIsStudent(v bool) *UserUpdate {
	_u.mutation.SetIsStudent(v)
	return _u
}

// SetNillableIsStudent sets the "is_student" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsStudent(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsStudent(*v)
	}
	return _u
}

// SetIsYouth sets the "is_youth" field.
func (_u *UserUpdate) SetIsYouth(v bool) *UserUpdate {
	_u.mutation.SetIsYouth(v)
	return _u
}

// SetNillableIsYouth sets the "is_youth" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsYouth(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsYouth(*v)
	}
	return _u
}

// SetIsPregnant sets the "is_pregnant" field.
func (_u *UserUpdate) SetIsPregnant(v bool) *UserUpdate {
	_u.mutation.SetIsPregnant(v)
	return _u
}

// SetNillableIsPregnant sets the "is_pregnant" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsPregnant(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsPregnant(*v)
	}
	return _u
}

// SetIsBusiness sets the "is_business" field.
func (_u *UserUpdate) SetIsBusiness(v bool) *UserUpdate {
	_u.mutation.SetIsBusiness(v)
	return _u
}

// SetNillableIsBusiness sets the "is_business" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsBusiness(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsBusiness(*v)
	}
	return _u
}

// SetIsForeign sets the "is_foreign" field.
func (_u *UserUpdate) SetIsForeign(v bool) *UserUpdate {
	_u.mutation.SetIsForeign(v)
	return _u
}

// SetNillableIsForeign sets the "is_foreign" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsForeign(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsForeign(*v)
	}
	return _u
}

// SetIsDisabled sets the "is_disabled" field.
func (_u *UserUpdate) SetIsDisabled(v bool) *UserUpdate {
	_u.mutation.SetIsDisabled(v)
	return _u
}

// SetNillableIsDisabled sets the "is_disabled" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsDisabled(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsDisabled(*v)
	}
	return _u
}

// SetInterests sets the "interests" field.
func (_u *UserUpdate) SetInterests(v []string) *UserUpdate {
	_u.mutation.SetInterests(v)
	return _u
}

// AppendInterests appends value to the "interests" field.
func (_u *UserUpdate) AppendInterests(v []string) *UserUpdate {
	_u.mutation.AppendInterests(v)
	return _u
}

// ClearInterests clears the value of the "interests" field.
func (_u *UserUpdate) ClearInterests() *UserUpdate {
	_u.mutation.ClearInterests()
	return _u
}

// AddPolicyMatchIDs adds the "policy_matches" edge to the PolicyMatch entity by IDs.
func (_u *UserUpdate) AddPolicyMatchIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddPolicyMatchIDs(ids...)
	return _u
}

// AddPolicyMatches adds the "policy_matches" edges to the PolicyMatch entity.
func (_u *UserUpdate) AddPolicyMatches(v ...*PolicyMatch) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPolicyMatchIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_u *UserUpdate) AddNotificationIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddNotificationIDs(ids...)
	return _u
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_u *UserUpdate) AddNotifications(v ...*Notification) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearPolicyMatches clears all "policy_matches" edges to the PolicyMatch entity.
func (_u *UserUpdate) ClearPolicyMatches() *UserUpdate {
	_u.mutation.ClearPolicyMatches()
	return _u
}

// RemovePolicyMatchIDs removes the "policy_matches" edge to PolicyMatch entities by IDs.
func (_u *UserUpdate) RemovePolicyMatchIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemovePolicyMatchIDs(ids...)
	return _u
}

// RemovePolicyMatches removes "policy_matches" edges to PolicyMatch entities.
func (_u *UserUpdate) RemovePolicyMatches(v ...*PolicyMatch) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePolicyMatchIDs(ids...)
}

// ClearNotifications clears all "notifications" edges to the Notification entity.
func (_u *UserUpdate) ClearNotifications() *UserUpdate {
	_u.mutation.ClearNotifications()
	return _u
}

// RemoveNotificationIDs removes the "notifications" edge to Notification entities by IDs.
func (_u *UserUpdate) RemoveNotificationIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveNotificationIDs(ids...)
	return _u
}

// RemoveNotifications removes "notifications" edges to Notification entities.
func (_u *UserUpdate) RemoveNotifications(v ...*Notification) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Gender(); ok {
		if err := user.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "User.gender": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Age(); ok {
		_spec.SetField(user.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAge(); ok {
		_spec.AddField(user.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RegionCode(); ok {
		_spec.SetField(user.FieldRegionCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRegionCode(); ok {
		_spec.AddField(user.FieldRegionCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(user.FieldGender, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsStudent(); ok {
		_spec.SetField(user.FieldIsStudent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsYouth(); ok {
		_spec.SetField(user.FieldIsYouth, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPregnant(); ok {
		_spec.SetField(user.FieldIsPregnant, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsBusiness(); ok {
		_spec.SetField(user.FieldIsBusiness, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsForeign(); ok {
		_spec.SetField(user.FieldIsForeign, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDisabled(); ok {
		_spec.SetField(user.FieldIsDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Interests(); ok {
		_spec.SetField(user.FieldInterests, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedInterests(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldInterests, value)
		})
	}
	if _u.mutation.InterestsCleared() {
		_spec.ClearField(user.FieldInterests, field.TypeJSON)
	}
	if _u.mutation.PolicyMatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PolicyMatchesTable,
			Columns: []string{user.PolicyMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPolicyMatchesIDs(); len(nodes) > 0 && !_u.mutation.PolicyMatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PolicyMatchesTable,
			Columns: []string{user.PolicyMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PolicyMatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PolicyMatchesTable,
			Columns: []string{user.PolicyMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationsIDs(); len(nodes) > 0 && !_u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserUpdateOne) SetPassword(v string) *UserUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePassword(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetAge sets the "age" field.
func (_u *UserUpdateOne) SetAge(v int) *UserUpdateOne {
	_u.mutation.ResetAge()
	_u.mutation.SetAge(v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAge(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *UserUpdateOne) AddAge(v int) *UserUpdateOne {
	_u.mutation.AddAge(v)
	return _u
}

// SetRegionCode sets the "region_code" field.
func (_u *UserUpdateOne) SetRegionCode(v int) *UserUpdateOne {
	_u.mutation.ResetRegionCode()
	_u.mutation.SetRegionCode(v)
	return _u
}

// SetNillableRegionCode sets the "region_code" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRegionCode(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetRegionCode(*v)
	}
	return _u
}

// AddRegionCode adds value to the "region_code" field.
func (_u *UserUpdateOne) AddRegionCode(v int) *UserUpdateOne {
	_u.mutation.AddRegionCode(v)
	return _u
}

// SetGender sets the "gender" field.
func (_u *UserUpdateOne) SetGender(v user.Gender) *UserUpdateOne {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGender(v *user.Gender) *UserUpdateOne {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// SetIsStudent sets the "is_student" field.
func (_u *UserUpdateOne) SetIsStudent(v bool) *UserUpdateOne {
	_u.mutation.SetIsStudent(v)
	return _u
}

// SetNillableIsStudent sets the "is_student" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsStudent(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsStudent(*v)
	}
	return _u
}

// SetIsYouth sets the "is_youth" field.
func (_u *UserUpdateOne) SetIsYouth(v bool) *UserUpdateOne {
	_u.mutation.SetIsYouth(v)
	return _u
}

// SetNillableIsYouth sets the "is_youth" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsYouth(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsYouth(*v)
	}
	return _u
}

// SetIsPregnant sets the "is_pregnant" field.
func (_u *UserUpdateOne) SetIsPregnant(v bool) *UserUpdateOne {
	_u.mutation.SetIsPregnant(v)
	return _u
}

// SetNillableIsPregnant sets the "is_pregnant" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsPregnant(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsPregnant(*v)
	}
	return _u
}

// SetIsBusiness sets the "is_business" field.
func (_u *UserUpdateOne) SetIsBusiness(v bool) *UserUpdateOne {
	_u.mutation.SetIsBusiness(v)
	return _u
}

// SetNillableIsBusiness sets the "is_business" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsBusiness(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsBusiness(*v)
	}
	return _u
}

// SetIsForeign sets the "is_foreign" field.
func (_u *UserUpdateOne) SetIsForeign(v bool) *UserUpdateOne {
	_u.mutation.SetIsForeign(v)
	return _u
}

// SetNillableIsForeign sets the "is_foreign" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsForeign(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsForeign(*v)
	}
	return _u
}

// SetIsDisabled sets the "is_disabled" field.
func (_u *UserUpdateOne) SetIsDisabled(v bool) *UserUpdateOne {
	_u.mutation.SetIsDisabled(v)
	return _u
}

// SetNillableIsDisabled sets the "is_disabled" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsDisabled(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsDisabled(*v)
	}
	return _u
}

// SetInterests sets the "interests" field.
func (_u *UserUpdateOne) SetInterests(v []string) *UserUpdateOne {
	_u.mutation.SetInterests(v)
	return _u
}

// AppendInterests appends value to the "interests" field.
func (_u *UserUpdateOne) AppendInterests(v []string) *UserUpdateOne {
	_u.mutation.AppendInterests(v)
	return _u
}

// ClearInterests clears the value of the "interests" field.
func (_u *UserUpdateOne) ClearInterests() *UserUpdateOne {
	_u.mutation.ClearInterests()
	return _u
}

// AddPolicyMatchIDs adds the "policy_matches" edge to the PolicyMatch entity by IDs.
func (_u *UserUpdateOne) AddPolicyMatchIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddPolicyMatchIDs(ids...)
	return _u
}

// AddPolicyMatches adds the "policy_matches" edges to the PolicyMatch entity.
func (_u *UserUpdateOne) AddPolicyMatches(v ...*PolicyMatch) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPolicyMatchIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_u *UserUpdateOne) AddNotificationIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddNotificationIDs(ids...)
	return _u
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_u *UserUpdateOne) AddNotifications(v ...*Notification) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearPolicyMatches clears all "policy_matches" edges to the PolicyMatch entity.
func (_u *UserUpdateOne) ClearPolicyMatches() *UserUpdateOne {
	_u.mutation.ClearPolicyMatches()
	return _u
}

// RemovePolicyMatchIDs removes the "policy_matches" edge to PolicyMatch entities by IDs.
func (_u *UserUpdateOne) RemovePolicyMatchIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemovePolicyMatchIDs(ids...)
	return _u
}

// RemovePolicyMatches removes "policy_matches" edges to PolicyMatch entities.
func (_u *UserUpdateOne) RemovePolicyMatches(v ...*PolicyMatch) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePolicyMatchIDs(ids...)
}

// ClearNotifications clears all "notifications" edges to the Notification entity.
func (_u *UserUpdateOne) ClearNotifications() *UserUpdateOne {
	_u.mutation.ClearNotifications()
	return _u
}

// RemoveNotificationIDs removes the "notifications" edge to Notification entities by IDs.
func (_u *UserUpdateOne) RemoveNotificationIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveNotificationIDs(ids...)
	return _u
}

// RemoveNotifications removes "notifications" edges to Notification entities.
func (_u *UserUpdateOne) RemoveNotifications(v ...*Notification) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Gender(); ok {
		if err := user.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "User.gender": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Age(); ok {
		_spec.SetField(user.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAge(); ok {
		_spec.AddField(user.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RegionCode(); ok {
		_spec.SetField(user.FieldRegionCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRegionCode(); ok {
		_spec.AddField(user.FieldRegionCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(user.FieldGender, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsStudent(); ok {
		_spec.SetField(user.FieldIsStudent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsYouth(); ok {
		_spec.SetField(user.FieldIsYouth, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPregnant(); ok {
		_spec.SetField(user.FieldIsPregnant, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsBusiness(); ok {
		_spec.SetField(user.FieldIsBusiness, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsForeign(); ok {
		_spec.SetField(user.FieldIsForeign, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDisabled(); ok {
		_spec.SetField(user.FieldIsDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Interests(); ok {
		_spec.SetField(user.FieldInterests, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedInterests(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldInterests, value)
		})
	}
	if _u.mutation.InterestsCleared() {
		_spec.ClearField(user.FieldInterests, field.TypeJSON)
	}
	if _u.mutation.PolicyMatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PolicyMatchesTable,
			Columns: []string{user.PolicyMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPolicyMatchesIDs(); len(nodes) > 0 && !_u.mutation.PolicyMatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PolicyMatchesTable,
			Columns: []string{user.PolicyMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PolicyMatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PolicyMatchesTable,
			Columns: []string{user.PolicyMatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(policymatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationsIDs(); len(nodes) > 0 && !_u.mutation.NotificationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: []string{user.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
