// Code generated by ent, DO NOT EDIT.

package policymatch

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the policymatch type in the database.
	Label = "policy_match"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMatch holds the string denoting the match field in the database.
	FieldMatch = "match"
	// FieldProbability holds the string denoting the probability field in the database.
	FieldProbability = "probability"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// EdgePolicy holds the string denoting the policy edge name in mutations.
	EdgePolicy = "policy"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the policymatch in the database.
	Table = "policy_matches"
	// PolicyTable is the table that holds the policy relation/edge.
	PolicyTable = "policy_matches"
	// PolicyInverseTable is the table name for the GovernmentPolicy entity.
	// It exists in this package in order to avoid circular dependency with the "governmentpolicy" package.
	PolicyInverseTable = "government_policies"
	// PolicyColumn is the table column denoting the policy relation/edge.
	PolicyColumn = "government_policy_matches"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "policy_matches"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_policy_matches"
)

// Columns holds all SQL columns for policymatch fields.
var Columns = []string{
	FieldID,
	FieldMatch,
	FieldProbability,
	FieldComment,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "policy_matches"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"government_policy_matches",
	"user_policy_matches",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Match defines the type for the "match" enum field.
type Match string

// Match values.
const (
	MatchPOSSIBLE   Match = "POSSIBLE"
	MatchUNCERTAIN  Match = "UNCERTAIN"
	MatchIMPOSSIBLE Match = "IMPOSSIBLE"
)

func (m Match) String() string {
	return string(m)
}

// MatchValidator is a validator for the "match" field enum values. It is called by the builders before save.
func MatchValidator(m Match) error {
	switch m {
	case MatchPOSSIBLE, MatchUNCERTAIN, MatchIMPOSSIBLE:
		return nil
	default:
		return fmt.Errorf("policymatch: invalid enum value for match field: %q", m)
	}
}

// OrderOption defines the ordering options for the PolicyMatch queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMatch orders the results by the match field.
func ByMatch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatch, opts...).ToFunc()
}

// ByProbability orders the results by the probability field.
func ByProbability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbability, opts...).ToFunc()
}

// ByComment orders the results by the comment field.
func ByComment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComment, opts...).ToFunc()
}

// ByPolicyField orders the results by policy field.
func ByPolicyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPolicyStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newPolicyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PolicyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PolicyTable, PolicyColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
