// Code generated by ent, DO NOT EDIT.

package policymatch

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/janghanul090801/pico-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldLTE(FieldID, id))
}

// Probability applies equality check predicate on the "probability" field. It's identical to ProbabilityEQ.
func Probability(v int) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldEQ(FieldProbability, v))
}

// Comment applies equality check predicate on the "comment" field. It's identical to CommentEQ.
func Comment(v string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldEQ(FieldComment, v))
}

// MatchEQ applies the EQ predicate on the "match" field.
func MatchEQ(v Match) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldEQ(FieldMatch, v))
}

// MatchNEQ applies the NEQ predicate on the "match" field.
func MatchNEQ(v Match) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldNEQ(FieldMatch, v))
}

// MatchIn applies the In predicate on the "match" field.
func MatchIn(vs ...Match) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldIn(FieldMatch, vs...))
}

// MatchNotIn applies the NotIn predicate on the "match" field.
func MatchNotIn(vs ...Match) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldNotIn(FieldMatch, vs...))
}

// ProbabilityEQ applies the EQ predicate on the "probability" field.
func ProbabilityEQ(v int) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldEQ(FieldProbability, v))
}

// ProbabilityNEQ applies the NEQ predicate on the "probability" field.
func ProbabilityNEQ(v int) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldNEQ(FieldProbability, v))
}

// ProbabilityIn applies the In predicate on the "probability" field.
func ProbabilityIn(vs ...int) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldIn(FieldProbability, vs...))
}

// ProbabilityNotIn applies the NotIn predicate on the "probability" field.
func ProbabilityNotIn(vs ...int) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldNotIn(FieldProbability, vs...))
}

// ProbabilityGT applies the GT predicate on the "probability" field.
func ProbabilityGT(v int) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldGT(FieldProbability, v))
}

// ProbabilityGTE applies the GTE predicate on the "probability" field.
func ProbabilityGTE(v int) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldGTE(FieldProbability, v))
}

// ProbabilityLT applies the LT predicate on the "probability" field.
func ProbabilityLT(v int) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldLT(FieldProbability, v))
}

// ProbabilityLTE applies the LTE predicate on the "probability" field.
func ProbabilityLTE(v int) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldLTE(FieldProbability, v))
}

// ProbabilityIsNil applies the IsNil predicate on the "probability" field.
func ProbabilityIsNil() predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldIsNull(FieldProbability))
}

// ProbabilityNotNil applies the NotNil predicate on the "probability" field.
func ProbabilityNotNil() predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldNotNull(FieldProbability))
}

// CommentEQ applies the EQ predicate on the "comment" field.
func CommentEQ(v string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldEQ(FieldComment, v))
}

// CommentNEQ applies the NEQ predicate on the "comment" field.
func CommentNEQ(v string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldNEQ(FieldComment, v))
}

// CommentIn applies the In predicate on the "comment" field.
func CommentIn(vs ...string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldIn(FieldComment, vs...))
}

// CommentNotIn applies the NotIn predicate on the "comment" field.
func CommentNotIn(vs ...string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldNotIn(FieldComment, vs...))
}

// CommentGT applies the GT predicate on the "comment" field.
func CommentGT(v string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldGT(FieldComment, v))
}

// CommentGTE applies the GTE predicate on the "comment" field.
func CommentGTE(v string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldGTE(FieldComment, v))
}

// CommentLT applies the LT predicate on the "comment" field.
func CommentLT(v string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldLT(FieldComment, v))
}

// CommentLTE applies the LTE predicate on the "comment" field.
func CommentLTE(v string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldLTE(FieldComment, v))
}

// CommentContains applies the Contains predicate on the "comment" field.
func CommentContains(v string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldContains(FieldComment, v))
}

// CommentHasPrefix applies the HasPrefix predicate on the "comment" field.
func CommentHasPrefix(v string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldHasPrefix(FieldComment, v))
}

// CommentHasSuffix applies the HasSuffix predicate on the "comment" field.
func CommentHasSuffix(v string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldHasSuffix(FieldComment, v))
}

// CommentIsNil applies the IsNil predicate on the "comment" field.
func CommentIsNil() predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldIsNull(FieldComment))
}

// CommentNotNil applies the NotNil predicate on the "comment" field.
func CommentNotNil() predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldNotNull(FieldComment))
}

// CommentEqualFold applies the EqualFold predicate on the "comment" field.
func CommentEqualFold(v string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldEqualFold(FieldComment, v))
}

// CommentContainsFold applies the ContainsFold predicate on the "comment" field.
func CommentContainsFold(v string) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.FieldContainsFold(FieldComment, v))
}

// HasPolicy applies the HasEdge predicate on the "policy" edge.
func HasPolicy() predicate.PolicyMatch {
	return predicate.PolicyMatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PolicyTable, PolicyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPolicyWith applies the HasEdge predicate on the "policy" edge with a given conditions (other predicates).
func HasPolicyWith(preds ...predicate.GovernmentPolicy) predicate.PolicyMatch {
	return predicate.PolicyMatch(func(s *sql.Selector) {
		step := newPolicyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PolicyMatch {
	return predicate.PolicyMatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PolicyMatch {
	return predicate.PolicyMatch(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PolicyMatch) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PolicyMatch) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PolicyMatch) predicate.PolicyMatch {
	return predicate.PolicyMatch(sql.NotPredicates(p))
}
