// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldRegionCode holds the string denoting the region_code field in the database.
	FieldRegionCode = "region_code"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// FieldIsStudent holds the string denoting the is_student field in the database.
	FieldIsStudent = "is_student"
	// FieldIsYouth holds the string denoting the is_youth field in the database.
	FieldIsYouth = "is_youth"
	// FieldIsPregnant holds the string denoting the is_pregnant field in the database.
	FieldIsPregnant = "is_pregnant"
	// FieldIsBusiness holds the string denoting the is_business field in the database.
	FieldIsBusiness = "is_business"
	// FieldIsForeign holds the string denoting the is_foreign field in the database.
	FieldIsForeign = "is_foreign"
	// FieldIsDisabled holds the string denoting the is_disabled field in the database.
	FieldIsDisabled = "is_disabled"
	// FieldInterests holds the string denoting the interests field in the database.
	FieldInterests = "interests"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgePolicyMatches holds the string denoting the policy_matches edge name in mutations.
	EdgePolicyMatches = "policy_matches"
	// EdgeNotifications holds the string denoting the notifications edge name in mutations.
	EdgeNotifications = "notifications"
	// EdgeFavorites holds the string denoting the favorites edge name in mutations.
	EdgeFavorites = "favorites"
	// Table holds the table name of the user in the database.
	Table = "users"
	// PolicyMatchesTable is the table that holds the policy_matches relation/edge.
	PolicyMatchesTable = "policy_matches"
	// PolicyMatchesInverseTable is the table name for the PolicyMatch entity.
	// It exists in this package in order to avoid circular dependency with the "policymatch" package.
	PolicyMatchesInverseTable = "policy_matches"
	// PolicyMatchesColumn is the table column denoting the policy_matches relation/edge.
	PolicyMatchesColumn = "user_policy_matches"
	// NotificationsTable is the table that holds the notifications relation/edge.
	NotificationsTable = "notifications"
	// NotificationsInverseTable is the table name for the Notification entity.
	// It exists in this package in order to avoid circular dependency with the "notification" package.
	NotificationsInverseTable = "notifications"
	// NotificationsColumn is the table column denoting the notifications relation/edge.
	NotificationsColumn = "user_notifications"
	// FavoritesTable is the table that holds the favorites relation/edge.
	FavoritesTable = "favorites"
	// FavoritesInverseTable is the table name for the Favorite entity.
	// It exists in this package in order to avoid circular dependency with the "favorite" package.
	FavoritesInverseTable = "favorites"
	// FavoritesColumn is the table column denoting the favorites relation/edge.
	FavoritesColumn = "user_favorites"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPassword,
	FieldAge,
	FieldRegionCode,
	FieldGender,
	FieldIsStudent,
	FieldIsYouth,
	FieldIsPregnant,
	FieldIsBusiness,
	FieldIsForeign,
	FieldIsDisabled,
	FieldInterests,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// DefaultIsStudent holds the default value on creation for the "is_student" field.
	DefaultIsStudent bool
	// DefaultIsYouth holds the default value on creation for the "is_youth" field.
	DefaultIsYouth bool
	// DefaultIsPregnant holds the default value on creation for the "is_pregnant" field.
	DefaultIsPregnant bool
	// DefaultIsBusiness holds the default value on creation for the "is_business" field.
	DefaultIsBusiness bool
	// DefaultIsForeign holds the default value on creation for the "is_foreign" field.
	DefaultIsForeign bool
	// DefaultIsDisabled holds the default value on creation for the "is_disabled" field.
	DefaultIsDisabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Gender defines the type for the "gender" enum field.
type Gender string

// Gender values.
const (
	GenderMALE   Gender = "MALE"
	GenderFEMALE Gender = "FEMALE"
	GenderOTHER  Gender = "OTHER"
)

func (ge Gender) String() string {
	return string(ge)
}

// GenderValidator is a validator for the "gender" field enum values. It is called by the builders before save.
func GenderValidator(ge Gender) error {
	switch ge {
	case GenderMALE, GenderFEMALE, GenderOTHER:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for gender field: %q", ge)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByAge orders the results by the age field.
func ByAge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAge, opts...).ToFunc()
}

// ByRegionCode orders the results by the region_code field.
func ByRegionCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegionCode, opts...).ToFunc()
}

// ByGender orders the results by the gender field.
func ByGender(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGender, opts...).ToFunc()
}

// ByIsStudent orders the results by the is_student field.
func ByIsStudent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsStudent, opts...).ToFunc()
}

// ByIsYouth orders the results by the is_youth field.
func ByIsYouth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsYouth, opts...).ToFunc()
}

// ByIsPregnant orders the results by the is_pregnant field.
func ByIsPregnant(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPregnant, opts...).ToFunc()
}

// ByIsBusiness orders the results by the is_business field.
func ByIsBusiness(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsBusiness, opts...).ToFunc()
}

// ByIsForeign orders the results by the is_foreign field.
func ByIsForeign(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsForeign, opts...).ToFunc()
}

// ByIsDisabled orders the results by the is_disabled field.
func ByIsDisabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDisabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByPolicyMatchesCount orders the results by policy_matches count.
func ByPolicyMatchesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPolicyMatchesStep(), opts...)
	}
}

// ByPolicyMatches orders the results by policy_matches terms.
func ByPolicyMatches(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPolicyMatchesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByNotificationsCount orders the results by notifications count.
func ByNotificationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotificationsStep(), opts...)
	}
}

// ByNotifications orders the results by notifications terms.
func ByNotifications(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFavoritesCount orders the results by favorites count.
func ByFavoritesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFavoritesStep(), opts...)
	}
}

// ByFavorites orders the results by favorites terms.
func ByFavorites(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFavoritesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPolicyMatchesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PolicyMatchesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PolicyMatchesTable, PolicyMatchesColumn),
	)
}
func newNotificationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotificationsTable, NotificationsColumn),
	)
}
func newFavoritesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FavoritesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FavoritesTable, FavoritesColumn),
	)
}
